# Cadence MMMC View Definition File
# Auto-generated by CBflow mmmc-manager from mmmc_config.tcl

# ----------------------------------------------------------------------
# Library Sets
# ----------------------------------------------------------------------

create_library_set -name ff_1p10v_125c \
    -timing [list ${::lib_dir}/ff_1p10v_125c_ccs.lib]

create_library_set -name ff_1p10v_25c \
    -timing [list ${::lib_dir}/ff_1p10v_25c_ccs.lib]

create_library_set -name ff_1p10v_m40c \
    -timing [list ${::lib_dir}/ff_1p10v_m40c_ccs.lib]

create_library_set -name ss_0p80v_125c \
    -timing [list ${::lib_dir}/ss_0p80v_125c_ccs.lib]

create_library_set -name ss_0p80v_m40c \
    -timing [list ${::lib_dir}/ss_0p80v_m40c_ccs.lib]

create_library_set -name ss_0p90v_125c \
    -timing [list ${::lib_dir}/ss_0p90v_125c_ccs.lib]

create_library_set -name ss_0p90v_m40c \
    -timing [list ${::lib_dir}/ss_0p90v_m40c_ccs.lib]

create_library_set -name tt_0p90v_125c \
    -timing [list ${::lib_dir}/tt_0p90v_125c_ccs.lib]

create_library_set -name tt_0p90v_25c \
    -timing [list ${::lib_dir}/tt_0p90v_25c_ccs.lib]

create_library_set -name tt_0p90v_m40c \
    -timing [list ${::lib_dir}/tt_0p90v_m40c_ccs.lib]

# ----------------------------------------------------------------------
# RC Corners
# ----------------------------------------------------------------------

create_rc_corner -name rc_max \
    -T 125 \
    -preRoute_res 1.15 \
    -preRoute_cap 1.10 \
    -postRoute_res 1.15 \
    -postRoute_cap 1.10 \
    -qx_tech_file [list ${::tech_dir}/qrc/rc_max/qrcTechFile]

create_rc_corner -name rc_min \
    -T -40 \
    -preRoute_res 0.85 \
    -preRoute_cap 0.90 \
    -postRoute_res 0.85 \
    -postRoute_cap 0.90 \
    -qx_tech_file [list ${::tech_dir}/qrc/rc_min/qrcTechFile]

create_rc_corner -name rc_typ \
    -T 25 \
    -preRoute_res 1.00 \
    -preRoute_cap 1.00 \
    -postRoute_res 1.00 \
    -postRoute_cap 1.00 \
    -qx_tech_file [list ${::tech_dir}/qrc/rc_typ/qrcTechFile]

# ----------------------------------------------------------------------
# Constraint Modes
# ----------------------------------------------------------------------

create_constraint_mode -name func_mode -sdc_files [list ${design_name}_func.sdc]

create_constraint_mode -name test_mode -sdc_files [list ${design_name}_test.sdc]

# ----------------------------------------------------------------------
# Delay Corners
# ----------------------------------------------------------------------

create_delay_corner -name func_ff_1p10v_rcmin_125c_dc \
    -library_set ff_1p10v_125c \
    -rc_corner rc_min

create_delay_corner -name func_ff_1p10v_rcmin_25c_dc \
    -library_set ff_1p10v_25c \
    -rc_corner rc_min

create_delay_corner -name func_ff_1p10v_rcmin_m40c_dc \
    -library_set ff_1p10v_m40c \
    -rc_corner rc_min

create_delay_corner -name func_ss_0p80v_rcmax_125c_dc \
    -library_set ss_0p80v_125c \
    -rc_corner rc_max

create_delay_corner -name func_ss_0p80v_rcmax_m40c_dc \
    -library_set ss_0p80v_m40c \
    -rc_corner rc_max

create_delay_corner -name func_ss_0p90v_rcmax_125c_dc \
    -library_set ss_0p90v_125c \
    -rc_corner rc_max

create_delay_corner -name func_ss_0p90v_rcmax_m40c_dc \
    -library_set ss_0p90v_m40c \
    -rc_corner rc_max

create_delay_corner -name func_tt_0p90v_rctyp_125c_dc \
    -library_set tt_0p90v_125c \
    -rc_corner rc_typ

create_delay_corner -name func_tt_0p90v_rctyp_25c_dc \
    -library_set tt_0p90v_25c \
    -rc_corner rc_typ

create_delay_corner -name func_tt_0p90v_rctyp_m40c_dc \
    -library_set tt_0p90v_m40c \
    -rc_corner rc_typ

create_delay_corner -name test_ff_1p10v_rcmin_125c_dc \
    -library_set ff_1p10v_125c \
    -rc_corner rc_min

create_delay_corner -name test_ff_1p10v_rcmin_25c_dc \
    -library_set ff_1p10v_25c \
    -rc_corner rc_min

create_delay_corner -name test_ff_1p10v_rcmin_m40c_dc \
    -library_set ff_1p10v_m40c \
    -rc_corner rc_min

create_delay_corner -name test_ss_0p80v_rcmax_125c_dc \
    -library_set ss_0p80v_125c \
    -rc_corner rc_max

create_delay_corner -name test_ss_0p80v_rcmax_m40c_dc \
    -library_set ss_0p80v_m40c \
    -rc_corner rc_max

create_delay_corner -name test_ss_0p90v_rcmax_125c_dc \
    -library_set ss_0p90v_125c \
    -rc_corner rc_max

create_delay_corner -name test_ss_0p90v_rcmax_m40c_dc \
    -library_set ss_0p90v_m40c \
    -rc_corner rc_max

create_delay_corner -name test_tt_0p90v_rctyp_125c_dc \
    -library_set tt_0p90v_125c \
    -rc_corner rc_typ

create_delay_corner -name test_tt_0p90v_rctyp_25c_dc \
    -library_set tt_0p90v_25c \
    -rc_corner rc_typ

create_delay_corner -name test_tt_0p90v_rctyp_m40c_dc \
    -library_set tt_0p90v_m40c \
    -rc_corner rc_typ

# ----------------------------------------------------------------------
# Analysis Views
# ----------------------------------------------------------------------

create_analysis_view -name func_ff_1p10v_rcmin_125c \
    -delay_corner func_ff_1p10v_rcmin_125c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_ff_1p10v_rcmin_25c \
    -delay_corner func_ff_1p10v_rcmin_25c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_ff_1p10v_rcmin_m40c \
    -delay_corner func_ff_1p10v_rcmin_m40c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_ss_0p80v_rcmax_125c \
    -delay_corner func_ss_0p80v_rcmax_125c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_ss_0p80v_rcmax_m40c \
    -delay_corner func_ss_0p80v_rcmax_m40c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_ss_0p90v_rcmax_125c \
    -delay_corner func_ss_0p90v_rcmax_125c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_ss_0p90v_rcmax_m40c \
    -delay_corner func_ss_0p90v_rcmax_m40c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_tt_0p90v_rctyp_125c \
    -delay_corner func_tt_0p90v_rctyp_125c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_tt_0p90v_rctyp_25c \
    -delay_corner func_tt_0p90v_rctyp_25c_dc \
    -constraint_mode func_mode

create_analysis_view -name func_tt_0p90v_rctyp_m40c \
    -delay_corner func_tt_0p90v_rctyp_m40c_dc \
    -constraint_mode func_mode

create_analysis_view -name test_ff_1p10v_rcmin_125c \
    -delay_corner test_ff_1p10v_rcmin_125c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_ff_1p10v_rcmin_25c \
    -delay_corner test_ff_1p10v_rcmin_25c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_ff_1p10v_rcmin_m40c \
    -delay_corner test_ff_1p10v_rcmin_m40c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_ss_0p80v_rcmax_125c \
    -delay_corner test_ss_0p80v_rcmax_125c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_ss_0p80v_rcmax_m40c \
    -delay_corner test_ss_0p80v_rcmax_m40c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_ss_0p90v_rcmax_125c \
    -delay_corner test_ss_0p90v_rcmax_125c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_ss_0p90v_rcmax_m40c \
    -delay_corner test_ss_0p90v_rcmax_m40c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_tt_0p90v_rctyp_125c \
    -delay_corner test_tt_0p90v_rctyp_125c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_tt_0p90v_rctyp_25c \
    -delay_corner test_tt_0p90v_rctyp_25c_dc \
    -constraint_mode test_mode

create_analysis_view -name test_tt_0p90v_rctyp_m40c \
    -delay_corner test_tt_0p90v_rctyp_m40c_dc \
    -constraint_mode test_mode

# ----------------------------------------------------------------------
# Active Analysis Views
# ----------------------------------------------------------------------

set_analysis_view -setup [list func_ss_0p80v_rcmax_125c func_ss_0p80v_rcmax_m40c func_ss_0p90v_rcmax_125c func_ss_0p90v_rcmax_m40c test_ss_0p80v_rcmax_125c test_ss_0p80v_rcmax_m40c test_ss_0p90v_rcmax_125c test_ss_0p90v_rcmax_m40c] -hold [list func_ff_1p10v_rcmin_125c func_ff_1p10v_rcmin_25c func_ff_1p10v_rcmin_m40c test_ff_1p10v_rcmin_125c test_ff_1p10v_rcmin_25c test_ff_1p10v_rcmin_m40c]
