#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# CBFlow — Input Resolution Utility
# Resolves downstream flow inputs from upstream run manifests or release tags.
#
# Priority: from_run (manifest) > release_tag > explicit paths (user_config)
#
# Usage:
#   source resolve_inputs.tcl
#   resolve_flow_inputs $flow_type $run_dir
# ═══════════════════════════════════════════════════════════════════════════════

namespace eval ::CBFlow::InputResolve {

    # Map: downstream flow input variable → manifest key
    variable handshake_map
    array set handshake_map {
        STA,netlist         "netlist,pt"
        STA,sdc_func_file   "sdc"
        STA,spef            "spef"
        STA,def_file        "def"

        LEC,netlist_revised "netlist,logic"
        LEC,netlist_golden  "netlist,logic"

        CLP,netlist         "netlist,vc_lp"
        CLP,upf_file        "upf"
        CLP,reference_netlist "netlist,vc_lp"

        PV,gds              "gds"
        PV,netlist           "netlist,lvs"
        PV,def_file         "def"

        EMIR,netlist        "netlist,logic"
        EMIR,def_file       "def"
        EMIR,spef           "spef"
        EMIR,gds            "gds"

        POPT,netlist        "netlist,pt"
        POPT,sdc            "sdc"
        POPT,spef           "spef"

        ECO,netlist         "netlist,logic"
        ECO,def_file        "def"
    }

    proc resolve_flow_inputs {flow_type run_dir} {
        set arr [string tolower $flow_type]

        # Check if already resolved (persisted file exists from setup subnode)
        set resolved_file "$run_dir/setup/resolved_inputs.tcl"
        if {[file exists $resolved_file]} {
            source $resolved_file
            puts "INFO: Loaded resolved inputs from $resolved_file"
            return 0
        }

        set resolved_vars [list]

        # ── Priority 1: from_run (read upstream manifest) ──
        if {[info exists ::${arr}(input,from_run)]} {
            set upstream_run [set ::${arr}(input,from_run)]
            if {$upstream_run ne "" && [file isdir $upstream_run]} {
                set count [resolve_from_run $flow_type $arr $upstream_run resolved_vars]
                if {$count > 0} {
                    puts "INFO: Resolved $count inputs from upstream run: $upstream_run"
                    _persist_resolved $resolved_file $resolved_vars
                    return $count
                }
            }
        }

        # ── Priority 2: release_tag ──
        if {[info exists ::${arr}(input,release_tag)]} {
            set tag [set ::${arr}(input,release_tag)]
            if {$tag ne ""} {
                set count [resolve_from_tag $flow_type $arr $tag $run_dir resolved_vars]
                if {$count > 0} {
                    puts "INFO: Resolved $count inputs from release tag: $tag"
                    _persist_resolved $resolved_file $resolved_vars
                    return $count
                }
            }
        }

        # ── Priority 3: explicit paths already in user_config — no action ──
        return 0
    }

    proc _persist_resolved {filepath vars_list} {
        # Write resolved variables to file so all subnodes can source it
        file mkdir [file dirname $filepath]
        set fh [open $filepath "w"]
        puts $fh "# Resolved inputs — auto-generated by resolve_flow_inputs"
        puts $fh "# Generated: [clock format [clock seconds]]"
        puts $fh ""
        foreach {varname value} $vars_list {
            puts $fh "set $varname \"$value\""
        }
        close $fh
        puts "INFO: Persisted resolved inputs to $filepath"
    }

    proc resolve_from_run {flow_type arr upstream_run {vars_var ""}} {
        variable handshake_map
        if {$vars_var ne ""} { upvar 1 $vars_var resolved_vars }

        # Search for output_manifest.tcl in upstream run
        set manifest_paths [list]
        foreach d [glob -nocomplain "$upstream_run/work/*/"] {
            foreach m [glob -nocomplain "${d}export_data*/results/output_manifest.tcl" \
                                        "${d}release_data*/results/output_manifest.tcl"] {
                lappend manifest_paths $m
            }
        }

        if {[llength $manifest_paths] == 0} {
            puts "WARNING: No output_manifest.tcl found in $upstream_run"
            return 0
        }

        set manifest_file [lindex [lsort -decreasing $manifest_paths] 0]
        puts "INFO: Reading upstream manifest: $manifest_file"

        if {[catch {source $manifest_file} err]} {
            puts "WARNING: Failed to read manifest: $err"
            return 0
        }

        set count 0
        set flow_upper [string toupper $flow_type]
        foreach {hkey mkey} [array get handshake_map] {
            set parts [split $hkey ","]
            if {[lindex $parts 0] ne $flow_upper} continue
            set hinput [lindex $parts 1]

            if {[info exists manifest($mkey)] && $manifest($mkey) ne ""} {
                set fpath $manifest($mkey)
                if {[file exists $fpath]} {
                    if {![info exists ::${arr}(input,${hinput})] || [set ::${arr}(input,${hinput})] eq ""} {
                        set ::${arr}(input,${hinput}) $fpath
                        puts "INFO:   ${arr}(input,${hinput}) = $fpath"
                        if {$vars_var ne ""} {
                            lappend resolved_vars "${arr}(input,${hinput})" $fpath
                        }
                        incr count
                    }
                }
            }
        }
        return $count
    }

    proc resolve_from_tag {flow_type arr tag run_dir} {
        variable handshake_map

        # Load release_config for base_dir and flow_input_handshake
        set release_base ""
        if {[info exists ::env(CONFIG_ROOT)] && [info exists ::env(FLOW_CONFIG_VERSION)]} {
            set rc_path "$::env(CONFIG_ROOT)/flow/$::env(FLOW_CONFIG_VERSION)/release_config.tcl"
            if {[file exists $rc_path]} {
                catch { source $rc_path }
                if {[info exists ::release(base_dir)]} { set release_base $::release(base_dir) }
            }
        }
        if {$release_base eq ""} {
            puts "WARNING: Cannot resolve release tag — release(base_dir) not set"
            return 0
        }

        set design_name ""
        if {[info exists ::flow(design_name)]} { set design_name $::flow(design_name) }

        set count 0
        set flow_upper [string toupper $flow_type]
        if {[array exists ::flow_input_handshake]} {
            foreach {hkey hval} [array get ::flow_input_handshake] {
                set parts [split $hkey ","]
                if {[lindex $parts 0] ne $flow_upper} continue
                set hinput [lindex $parts 1]

                set src_category [lindex $hval 1]
                set src_pattern [lindex $hval 2]
                set filename [string map [list \${design_name} $design_name] $src_pattern]
                set fpath [file join $release_base $tag $src_category $filename]

                if {[file exists $fpath]} {
                    if {![info exists ::${arr}(input,${hinput})] || [set ::${arr}(input,${hinput})] eq ""} {
                        set ::${arr}(input,${hinput}) $fpath
                        puts "INFO:   ${arr}(input,${hinput}) = $fpath (tag=$tag)"
                        incr count
                    }
                }
            }
        }
        return $count
    }

    # Generate output manifest for export_data/release_data validate subnodes.
    # Scans wherever the flow actually writes: outputs/, results/<flow>/, work/<flow>/export_data/
    proc generate_output_manifest {flow_type node_name run_dir} {
        set design_name ""
        if {[info exists ::flow(design_name)]} { set design_name $::flow(design_name) }
        set flow_lower [string tolower $flow_type]

        set results_dir "$run_dir/work/$flow_type/$node_name/results"
        file mkdir $results_dir
        set manifest_file "$results_dir/output_manifest.tcl"

        # Directories to scan (in priority order — first match wins per key)
        set search_dirs [list \
            "$run_dir/outputs" \
            "$run_dir/results/$flow_lower" \
            "$run_dir/results/$flow_type" \
            "$run_dir/work/$flow_type/$node_name/run" \
        ]

        set mf [open $manifest_file "w"]
        puts $mf "# Output Manifest — $flow_type $node_name"
        puts $mf "# Generated: [clock format [clock seconds]]"
        puts $mf "# Design: $design_name"
        puts $mf ""

        set count 0
        array set found {}

        # File patterns to search for: {suffix manifest_key}
        set patterns {
            ".v"              "netlist,logic"
            ".pt.v"           "netlist,pt"
            ".fm.v"           "netlist,fm"
            ".lvs.v"          "netlist,lvs"
            ".vc_lp.v"        "netlist,vc_lp"
            ".dc.v"           "netlist,dc"
            ".gds"            "gds"
            ".def"            "def"
            ".lef"            "lef"
            ".sdc"            "sdc"
            ".upf"            "upf"
            ".spef"           "spef"
            "_wscript"        "wscript"
            "_wscript_for_pt" "wscript_for_pt"
            "_routing_constraints" "routing_constraints"
            "_floorplan"      "floorplan"
            ".saif.ptpx.map"  "saif_ptpx_map"
            ".saif.fc.map"    "saif_fc_map"
        }

        foreach {suffix key} $patterns {
            if {[info exists found($key)]} continue
            foreach dir $search_dirs {
                if {![file isdir $dir]} continue
                # Direct match: <dir>/<design><suffix>
                set f "$dir/${design_name}${suffix}"
                if {[file exists $f]} {
                    puts $mf "set manifest($key) \"$f\""
                    set found($key) 1
                    incr count
                    break
                }
                # Subdirectory match: <dir>/netlist/<design><suffix>, <dir>/def/<design><suffix>, etc.
                foreach sub [glob -nocomplain -types d "$dir/*/"] {
                    set f2 "$sub${design_name}${suffix}"
                    if {[file exists $f2]} {
                        puts $mf "set manifest($key) \"$f2\""
                        set found($key) 1
                        incr count
                        break
                    }
                }
                if {[info exists found($key)]} break
                # Glob fallback for the suffix
                set matches [glob -nocomplain "$dir/${design_name}*${suffix}" "$dir/*/${design_name}*${suffix}"]
                if {[llength $matches] > 0} {
                    puts $mf "set manifest($key) \"[lindex $matches 0]\""
                    set found($key) 1
                    incr count
                    break
                }
            }
        }

        puts $mf ""
        puts $mf "set manifest(flow) \"$flow_type\""
        puts $mf "set manifest(node) \"$node_name\""
        puts $mf "set manifest(design) \"$design_name\""
        puts $mf "set manifest(run_dir) \"$run_dir\""
        puts $mf "set manifest(timestamp) \"[clock format [clock seconds]]\""
        puts $mf "set manifest(file_count) $count"
        close $mf

        puts "INFO: Output manifest: $manifest_file ($count files)"
        return $count
    }

    namespace export resolve_flow_inputs resolve_from_run generate_output_manifest
}

namespace import ::CBFlow::InputResolve::resolve_flow_inputs
namespace import ::CBFlow::InputResolve::resolve_from_run
namespace import ::CBFlow::InputResolve::generate_output_manifest
