#!/usr/bin/env tclsh
# CBFlow ATPG export_patterns — tessent

set run_dir $::env(CBFLOW_RUN_DIR)
source "$run_dir/.run.cbflow.tcl"
source "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/utils.tcl"

set FLOW_TYPE "ATPG"
set STAGE_NAME "export_patterns"
set NODE_NAME "${STAGE_NAME}1"

source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/config.tcl"
source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/setup.tcl"
setup_dirs $run_dir $FLOW_TYPE $NODE_NAME

set _rel "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/release_utils.tcl"
if {[file exists $_rel]} { source $_rel }

flow_proc export_patterns_run {
    handle_info "ATPG export_patterns (tessent) running..."
    # test_mode dummy outputs are auto-generated by handler_run/launch_utils.tcl.
    # Real-tool integration goes here.
    handle_info "ATPG export_patterns completed"
}
flow_proc export_patterns_flow { flow_exec export_patterns_run }
if {[info exists argv0] && $argv0 eq [info script]} { flow_exec export_patterns_flow } else { puts " ATPG export_patterns procedures loaded" }
exit
