set project(name) bumblebee
set project(phase) P0
set flow(type) SYNTH
set flow(design_name) cpu_core
set flow(run_name) varun
set flow(test_mode) true
set synth(input,rtl_filelist) /Users/vmerugu/projects/CBflow_clone/inputs/rtl.list
set synth(input,rtl_format) sverilog
set synth(input,sdc_func_file) /Users/vmerugu/projects/CBflow_clone/inputs/func.sdc
set synth(input,upf_file) /Users/vmerugu/projects/CBflow_clone/inputs/power.upf
