# Resolved inputs — auto-generated by resolve_flow_inputs
# Generated: Thu May 21 22:30:33 IST 2026

set sta(input,sdc_func_file) "/Users/vmerugu/projects/CBflow_clone/workarea_test/P0_run_SYNTH_PNR_test1/outputs/cpu_core_func.sdc"
set sta(input,def_file) "/Users/vmerugu/projects/CBflow_clone/workarea_test/P0_run_SYNTH_PNR_test1/outputs/cpu_core.def"
set sta(input,netlist) "/Users/vmerugu/projects/CBflow_clone/workarea_test/P0_run_SYNTH_PNR_test1/outputs/cpu_core.pt.v"
