# SPEF Manifest — generated by extraction validate
# Maps RC corners to their extracted SPEF files
# Generated: Tue May 26 13:58:04 IST 2026

set spef_map(rc_max) "/Users/vmerugu/projects/CBflow_clone/workarea/cpu_core/P0_run_STA_test1/work/STA/extraction1/rc_max/results/extraction1_rc_max.spef"
set spef_map(rc_max_cworst) "/Users/vmerugu/projects/CBflow_clone/workarea/cpu_core/P0_run_STA_test1/work/STA/extraction1/rc_max_cworst/results/extraction1_rc_max_cworst.spef"
set spef_map(rc_min) "/Users/vmerugu/projects/CBflow_clone/workarea/cpu_core/P0_run_STA_test1/work/STA/extraction1/rc_min/results/extraction1_rc_min.spef"
set spef_map(rc_typ) "/Users/vmerugu/projects/CBflow_clone/workarea/cpu_core/P0_run_STA_test1/work/STA/extraction1/rc_typ/results/extraction1_rc_typ.spef"

set spef_corners {rc_max rc_max_cworst rc_min rc_typ}
set spef_corner_count 4
