#!/usr/bin/env tclsh
# CBFlow SCAN_INSERT scan_export — tessent

set run_dir $::env(CBFLOW_RUN_DIR)
source "$run_dir/.run.cbflow.tcl"
source "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/utils.tcl"

set FLOW_TYPE "SCAN_INSERT"
set STAGE_NAME "scan_export"
set NODE_NAME "${STAGE_NAME}1"

source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/config.tcl"
source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/setup.tcl"
setup_dirs $run_dir $FLOW_TYPE $NODE_NAME

set _rel "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/release_utils.tcl"
if {[file exists $_rel]} { source $_rel }

flow_proc scan_export_run {
    handle_info "SCAN_INSERT scan_export (tessent) running..."
    # test_mode dummy outputs are auto-generated by handler_run/launch_utils.tcl.
    # Real-tool integration goes here.
    handle_info "SCAN_INSERT scan_export completed"
}
flow_proc scan_export_flow { flow_exec scan_export_run }
if {[info exists argv0] && $argv0 eq [info script]} { flow_exec scan_export_flow } else { puts " SCAN_INSERT scan_export procedures loaded" }
exit
