#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# DMSA Worker — Per-Scenario Timing Analysis Template
# Generated by dmsa_master.tcl for scenario: <SCENARIO_NAME>
#
# This script is executed by the PT DMSA worker process. The master substitutes
# all <PLACEHOLDER> values when generating per-scenario workers into
# work/POPT/dmsa_workers/<scenario_name>_worker.tcl
#
# Placeholder reference:
#   <SCENARIO_NAME>  — full scenario name (e.g. func_ss_0p76v_rcmax_150c)
#   <CORNER>         — process corner (ss, tt, ff)
#   <MODE>           — operating mode (func, test)
#   <VOLTAGE>        — voltage point (e.g. 0p76v)
#   <TEMPERATURE>    — temperature point (e.g. 150c)
#   <RC_CORNER>      — RC extraction corner (rcmax, rctyp, rcmin)
#   <LIB_SET>        — library set reference (e.g. ss_0p76v_150c)
#   <SDC_FILE>       — path to mode-specific SDC constraint file
#   <SPEF_FILE>      — path to corner-specific SPEF parasitic file
#   <RUN_DIR>        — run directory for this POPT execution
# ═══════════════════════════════════════════════════════════════════════════════

# ── Scenario context (substituted by dmsa_master.tcl) ──────────────────────
set ::SCENARIO_NAME  "<SCENARIO_NAME>"
set ::CORNER         "<CORNER>"
set ::MODE           "<MODE>"
set ::VOLTAGE        "<VOLTAGE>"
set ::TEMPERATURE    "<TEMPERATURE>"
set ::RC_CORNER      "<RC_CORNER>"
set ::LIB_SET        "<LIB_SET>"
set ::SDC_FILE       "<SDC_FILE>"
set ::SPEF_FILE      "<SPEF_FILE>"
set ::RUN_DIR        "<RUN_DIR>"

puts "INFO: DMSA Worker starting — scenario=$::SCENARIO_NAME"
puts "INFO:   Corner=$::CORNER  Mode=$::MODE  Voltage=$::VOLTAGE  Temp=$::TEMPERATURE"
puts "INFO:   RC=$::RC_CORNER  LibSet=$::LIB_SET"

# ── Read libraries for this corner ─────────────────────────────────────────
# Libraries are typically read by the master via link_library or read_db.
# The worker inherits the shared netlist from the master process.
# If corner-specific library overrides are needed, read them here.
#
# PT DMSA: The master session shares the design netlist. Each worker adds
# its corner-specific timing libraries via set_libs or read_db if the
# master has not already loaded them.
#
# Example (uncomment if per-worker lib loading is required):
#   if {[info exists library_sets(${::LIB_SET},timing)]} {
#       foreach lib $library_sets(${::LIB_SET},timing) {
#           if {[file exists $lib]} {
#               read_db $lib
#               puts "INFO:   Worker read_db: [file tail $lib]"
#           }
#       }
#   }

# ── Read parasitics ───────────────────────────────────────────────────────
# PT: read_parasitics -format spef <file>
# Corner-specific SPEF provides accurate RC for this PVT point.
if {$::SPEF_FILE ne "" && [file exists $::SPEF_FILE]} {
    puts "INFO:   Reading SPEF: [file tail $::SPEF_FILE]"
    read_parasitics -format spef $::SPEF_FILE
} else {
    puts "WARNING: SPEF not found for scenario $::SCENARIO_NAME: $::SPEF_FILE"
    puts "WARNING: Timing will use wireload models or master parasitics"
}

# ── Read constraints ──────────────────────────────────────────────────────
# PT: read_sdc <file>
# Mode-specific SDC defines clocks, I/O constraints, and false paths
# for this operating mode.
if {$::SDC_FILE ne "" && [file exists $::SDC_FILE]} {
    puts "INFO:   Reading SDC: [file tail $::SDC_FILE]"
    read_sdc $::SDC_FILE
} else {
    puts "WARNING: SDC not found for scenario $::SCENARIO_NAME: $::SDC_FILE"
}

# ── Set operating conditions ──────────────────────────────────────────────
# PT: set_operating_conditions -analysis_type on_chip_variation
# Apply OCV for accurate multi-scenario analysis.
set_operating_conditions -analysis_type on_chip_variation

# ── Propagate clocks (post-CTS designs) ───────────────────────────────────
# PT: set_propagated_clock [all_clocks]
# For post-route designs, use propagated (real) clock latencies.
if {[sizeof_collection [all_clocks]] > 0} {
    set_propagated_clock [all_clocks]
    puts "INFO:   Propagated clocks: [sizeof_collection [all_clocks]] clock(s)"
} else {
    puts "WARNING: No clocks found in scenario $::SCENARIO_NAME"
}

# ── Update timing ─────────────────────────────────────────────────────────
# PT: update_timing -full
# Full timing propagation for this corner/mode combination.
puts "INFO:   Running update_timing -full..."
update_timing -full

# ── Validate timing for this scenario ─────────────────────────────────────
# Quick sanity check — report WNS for this worker's corner.
set _worker_rpt_dir "$::RUN_DIR/reports/popt/dmsa"
catch { file mkdir $_worker_rpt_dir }

if {[catch {
    set _wns [get_attribute [get_timing_paths -delay_type max -max_paths 1] slack]
    puts "INFO:   Setup WNS: $_wns"
} err]} {
    set _wns "N/A"
    puts "WARNING: Could not extract WNS — $err"
}

if {[catch {
    set _hold_wns [get_attribute [get_timing_paths -delay_type min -max_paths 1] slack]
    puts "INFO:   Hold  WNS: $_hold_wns"
} err]} {
    set _hold_wns "N/A"
    puts "WARNING: Could not extract hold WNS — $err"
}

# ── Write per-scenario worker status ──────────────────────────────────────
set _status_file "$_worker_rpt_dir/${::SCENARIO_NAME}_worker_status.rpt"
if {[catch {
    set _sfh [open $_status_file w]
    puts $_sfh "DMSA Worker Status — $::SCENARIO_NAME"
    puts $_sfh "Generated: [clock format [clock seconds]]"
    puts $_sfh [string repeat "─" 50]
    puts $_sfh "Corner:      $::CORNER"
    puts $_sfh "Mode:        $::MODE"
    puts $_sfh "Voltage:     $::VOLTAGE"
    puts $_sfh "Temperature: $::TEMPERATURE"
    puts $_sfh "RC Corner:   $::RC_CORNER"
    puts $_sfh "Library Set: $::LIB_SET"
    puts $_sfh [string repeat "─" 50]
    puts $_sfh "Setup WNS:   $_wns"
    puts $_sfh "Hold  WNS:   $_hold_wns"
    puts $_sfh [string repeat "─" 50]
    close $_sfh
}]} {
    puts "WARNING: Could not write worker status file"
}

puts "INFO: DMSA Worker completed — scenario=$::SCENARIO_NAME"
