#!/usr/bin/env tclsh
# CBFlow ATPG coverage_report — testmax

set run_dir $::env(CBFLOW_RUN_DIR)
source "$run_dir/.run.cbflow.tcl"
source "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/utils.tcl"

set FLOW_TYPE "ATPG"
set STAGE_NAME "coverage_report"
set NODE_NAME "${STAGE_NAME}1"

source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/config.tcl"
source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/setup.tcl"
setup_dirs $run_dir $FLOW_TYPE $NODE_NAME

set _rel "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/release_utils.tcl"
if {[file exists $_rel]} { source $_rel }

flow_proc coverage_report_run {
    handle_info "ATPG coverage_report (testmax) running..."
    # test_mode dummy outputs are auto-generated by handler_run/launch_utils.tcl.
    # Real-tool integration goes here.
    handle_info "ATPG coverage_report completed"
}
flow_proc coverage_report_flow { flow_exec coverage_report_run }
if {[info exists argv0] && $argv0 eq [info script]} { flow_exec coverage_report_flow } else { puts " ATPG coverage_report procedures loaded" }
exit
