#!/usr/bin/env tclsh
# CBFlow DFT_INSERT init_dft — dft_compiler

set run_dir $::env(CBFLOW_RUN_DIR)
source "$run_dir/.run.cbflow.tcl"
source "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/utils.tcl"

set FLOW_TYPE "DFT_INSERT"
set STAGE_NAME "init_dft"
set NODE_NAME "${STAGE_NAME}1"

source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/config.tcl"
source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/setup.tcl"
setup_dirs $run_dir $FLOW_TYPE $NODE_NAME

set _rel "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/release_utils.tcl"
if {[file exists $_rel]} { source $_rel }

flow_proc init_dft_run {
    handle_info "DFT_INSERT init_dft (dft_compiler) running..."
    # test_mode dummy outputs are auto-generated by handler_run/launch_utils.tcl.
    # Real-tool integration goes here.
    handle_info "DFT_INSERT init_dft completed"
}
flow_proc init_dft_flow { flow_exec init_dft_run }
if {[info exists argv0] && $argv0 eq [info script]} { flow_exec init_dft_flow } else { puts " DFT_INSERT init_dft procedures loaded" }
exit
