# ── MMMC Node Scenario Assignments ──
# Generated by: cbflow flow mmmc-manager generate --tech gf_22nm
# Add/modify these in project_config.tcl
array set mmmc {
    init_design {
        setup {func_tt_0p80v_rctyp_150c}
        hold {func_tt_0p80v_rctyp_150c}
    }

    floorplan {
        setup {func_ss_0p76v_rcmax_150c}
        hold {func_ff_0p80v_rcmin_m40c}
    }

    powerplan {
        setup {func_ss_0p76v_rcmax_150c}
        hold {func_ff_0p80v_rcmin_m40c}
    }

    placement {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
        }
    }

    cts {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
            func_ss_0p76v_rcmax_m40c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
            func_ff_0p84v_rcmin_25c
        }
    }

    cts_opt {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
            func_ss_0p76v_rcmax_m40c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
            func_ff_0p84v_rcmin_25c
        }
    }

    route {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
            func_ss_0p76v_rcmax_m40c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
            func_ff_0p84v_rcmin_25c
        }
    }

    post_route {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
            func_ss_0p76v_rcmax_m40c
            func_ss_0p80v_rcmax_150c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
            func_ff_0p84v_rcmin_25c
            func_ff_0p84v_rcmin_m40c
        }
    }

    signoff {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
            func_ss_0p76v_rcmax_m40c
            func_ss_0p80v_rcmax_150c
            func_ss_0p80v_rcmax_25c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
            func_ff_0p84v_rcmin_25c
            func_ff_0p84v_rcmin_m40c
        }
    }

    synthesis {
        setup {
            func_ss_0p76v_rcmax_150c
            func_ss_0p76v_rcmax_25c
            func_ss_0p76v_rcmax_m40c
        }
        hold {
            func_ff_0p80v_rcmin_m40c
            func_ff_0p84v_rcmin_150c
        }
    }

}
