#!/usr/bin/env tclsh
# =============================================================================
# AUTO-GENERATED by: cbflow flow library-manager generate
# Tech: tsmc_7nm | Generated: 2026-06-02 22:53
# Source: /tmp/test_libs/tsmc_7nm
# Tracks: 6T 7.5T 9T | VTs: ulvt lvt svt hvt
# Corners: 3
# DO NOT EDIT — regenerate with: cbflow flow library-manager generate
# =============================================================================

# ── NDM per track per VT ──
set tech(6T,ulvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6tulvt.ndm"]
set tech(6T,lvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6tlvt.ndm"]
set tech(6T,svt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6tsvt.ndm"]
set tech(6T,hvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6thvt.ndm"]
set tech(7.5T,ulvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5tulvt.ndm"]
set tech(7.5T,lvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5tlvt.ndm"]
set tech(7.5T,svt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5tsvt.ndm"]
set tech(7.5T,hvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5thvt.ndm"]
set tech(9T,ulvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9tulvt.ndm"]
set tech(9T,lvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9tlvt.ndm"]
set tech(9T,svt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9tsvt.ndm"]
set tech(9T,hvt,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9thvt.ndm"]

# ── NDM shared ──
set tech(ndm,memory) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/ts1n07_memory.ndm"]
set tech(ndm,io) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tpbn07v_io.ndm"]
set tech(ndm,analog) [list]

# ── NDM combined per track ──
set tech(6T,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6tulvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6tlvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6tsvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp6thvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/ts1n07_memory.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tpbn07v_io.ndm"]
set tech(7.5T,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5tulvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5tlvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5tsvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp7p5thvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/ts1n07_memory.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tpbn07v_io.ndm"]
set tech(9T,ndm) [list "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9tulvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9tlvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9tsvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tcbn07bwp9thvt.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/ts1n07_memory.ndm" "/tmp/test_libs/tsmc_7nm/Back_End/ndm/tpbn07v_io.ndm"]

# ── DB per track per VT ──
set tech(6T,ulvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvttt0p80v25c.db"]
set tech(6T,lvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvttt0p80v25c.db"]
set tech(6T,svt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvttt0p80v25c.db"]
set tech(6T,hvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvttt0p80v25c.db"]
set tech(7.5T,ulvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvttt0p80v25c.db"]
set tech(7.5T,lvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvttt0p80v25c.db"]
set tech(7.5T,svt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvttt0p80v25c.db"]
set tech(7.5T,hvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvttt0p80v25c.db"]
set tech(9T,ulvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvttt0p80v25c.db"]
set tech(9T,lvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvttt0p80v25c.db"]
set tech(9T,svt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvttt0p80v25c.db"]
set tech(9T,hvt,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvttt0p80v25c.db"]

# ── DB shared ──
set tech(db,memory) [list ]
set tech(db,io) [list ]

# ── DB combined per track ──
set tech(6T,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvttt0p80v25c.db"]
set tech(7.5T,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvttt0p80v25c.db"]
set tech(9T,db) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvttt0p80v25c.db" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvttt0p80v25c.db"]

# ── lib_nom per track per VT ──

# ── lib_nom shared ──
set tech(lib_nom,memory) [list ]
set tech(lib_nom,io) [list ]

# ── lib_nom combined per track (from TT nominal: tt_0p80v_25c) ──
set tech(6T,lib_nom) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]
set tech(7.5T,lib_nom) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]
set tech(9T,lib_nom) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]

# ── LEF per track per VT ──
set tech(6T,ulvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6tulvt.lef"]
set tech(6T,lvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6tlvt.lef"]
set tech(6T,svt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6tsvt.lef"]
set tech(6T,hvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6thvt.lef"]
set tech(7.5T,ulvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5tulvt.lef"]
set tech(7.5T,lvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5tlvt.lef"]
set tech(7.5T,svt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5tsvt.lef"]
set tech(7.5T,hvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5thvt.lef"]
set tech(9T,ulvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9tulvt.lef"]
set tech(9T,lvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9tlvt.lef"]
set tech(9T,svt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9tsvt.lef"]
set tech(9T,hvt,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9thvt.lef"]

# ── LEF shared ──
set tech(lef,memory) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/ts1n07_memory.lef"]
set tech(lef,io) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tpbn07v_io.lef"]

# ── LEF combined per track ──
set tech(6T,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6tulvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6tlvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6tsvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp6thvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/ts1n07_memory.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tpbn07v_io.lef"]
set tech(7.5T,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5tulvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5tlvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5tsvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp7p5thvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/ts1n07_memory.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tpbn07v_io.lef"]
set tech(9T,lef) [list "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9tulvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9tlvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9tsvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tcbn07bwp9thvt.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/ts1n07_memory.lef" "/tmp/test_libs/tsmc_7nm/Back_End/lef/tpbn07v_io.lef"]

# ── Corners discovered ──
set tech(corners) {ff_0p88v_m40c ss_0p72v_125c tt_0p80v_25c}

# ── Timing libs per track per VT per corner ──
set tech(6T,ulvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvtff0p88vm40c_ccs.lib"]
set tech(6T,lvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvtff0p88vm40c_ccs.lib"]
set tech(6T,svt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvtff0p88vm40c_ccs.lib"]
set tech(6T,hvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvtff0p88vm40c_ccs.lib"]
set tech(6T,ulvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvtss0p72v125c_ccs.lib"]
set tech(6T,lvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvtss0p72v125c_ccs.lib"]
set tech(6T,svt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvtss0p72v125c_ccs.lib"]
set tech(6T,hvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvtss0p72v125c_ccs.lib"]
set tech(6T,ulvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvttt0p80v25c_ccs.lib"]
set tech(6T,lvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvttt0p80v25c_ccs.lib"]
set tech(6T,svt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvttt0p80v25c_ccs.lib"]
set tech(6T,hvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvttt0p80v25c_ccs.lib"]
set tech(7.5T,ulvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvtff0p88vm40c_ccs.lib"]
set tech(7.5T,lvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvtff0p88vm40c_ccs.lib"]
set tech(7.5T,svt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvtff0p88vm40c_ccs.lib"]
set tech(7.5T,hvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvtff0p88vm40c_ccs.lib"]
set tech(7.5T,ulvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvtss0p72v125c_ccs.lib"]
set tech(7.5T,lvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvtss0p72v125c_ccs.lib"]
set tech(7.5T,svt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvtss0p72v125c_ccs.lib"]
set tech(7.5T,hvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvtss0p72v125c_ccs.lib"]
set tech(7.5T,ulvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvttt0p80v25c_ccs.lib"]
set tech(7.5T,lvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvttt0p80v25c_ccs.lib"]
set tech(7.5T,svt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvttt0p80v25c_ccs.lib"]
set tech(7.5T,hvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvttt0p80v25c_ccs.lib"]
set tech(9T,ulvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvtff0p88vm40c_ccs.lib"]
set tech(9T,lvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvtff0p88vm40c_ccs.lib"]
set tech(9T,svt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvtff0p88vm40c_ccs.lib"]
set tech(9T,hvt,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvtff0p88vm40c_ccs.lib"]
set tech(9T,ulvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvtss0p72v125c_ccs.lib"]
set tech(9T,lvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvtss0p72v125c_ccs.lib"]
set tech(9T,svt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvtss0p72v125c_ccs.lib"]
set tech(9T,hvt,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvtss0p72v125c_ccs.lib"]
set tech(9T,ulvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvttt0p80v25c_ccs.lib"]
set tech(9T,lvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvttt0p80v25c_ccs.lib"]
set tech(9T,svt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvttt0p80v25c_ccs.lib"]
set tech(9T,hvt,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvttt0p80v25c_ccs.lib"]

# ── Timing libs shared per corner (memory + IO) ──
set tech(lib,ff_0p88v_m40c,timing,memory) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ff0p88vm40c.lib"]
set tech(lib,ff_0p88v_m40c,timing,io) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ff0p88vm40c.lib"]
set tech(lib,ss_0p72v_125c,timing,memory) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ss0p72v125c.lib"]
set tech(lib,ss_0p72v_125c,timing,io) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ss0p72v125c.lib"]
set tech(lib,tt_0p80v_25c,timing,memory) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib"]
set tech(lib,tt_0p80v_25c,timing,io) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]

# ── Timing combined per track per corner ──
set tech(6T,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ff0p88vm40c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ff0p88vm40c.lib"]
set tech(6T,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ss0p72v125c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ss0p72v125c.lib"]
set tech(6T,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tulvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tlvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6tsvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp6thvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]
set tech(7.5T,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ff0p88vm40c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ff0p88vm40c.lib"]
set tech(7.5T,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ss0p72v125c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ss0p72v125c.lib"]
set tech(7.5T,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tulvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tlvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5tsvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp7p5thvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]
set tech(9T,lib,ff_0p88v_m40c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvtff0p88vm40c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ff0p88vm40c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ff0p88vm40c.lib"]
set tech(9T,lib,ss_0p72v_125c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvtss0p72v125c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07ss0p72v125c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_ss0p72v125c.lib"]
set tech(9T,lib,tt_0p80v_25c,timing) [list "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tulvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tlvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9tsvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/stdcell/tcbn07bwp9thvttt0p80v25c_ccs.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/memory/ts1n07tt0p80v25c.lib" "/tmp/test_libs/tsmc_7nm/Front_End/timing/io/tpbn07v_tt0p80v25c.lib"]

