#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# CBflow Technology Configuration — TSMC N7 (7nm FinFET)
# ALL track heights (6T, 7.5T, 9T) in ONE file — flow picks via tech(track)
# Library sets auto-generated in lib_config.tcl by library-manager
# ═══════════════════════════════════════════════════════════════════════════════

set _tech_dir [file dirname [file normalize [info script]]]

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1: TECHNOLOGY IDENTITY
# ═══════════════════════════════════════════════════════════════════════════════

set tech(node)        "7nm"
set tech(process)     "TSMC N7"
set tech(foundry)     "TSMC"
set tech(metal_stack) "12M"
set tech(tracks_available) "6T 7.5T 9T"

# ── VT Variant Patterns (for dont_use selection + lib filtering) ───────
set tech(vt_variants_available) {svt lvt ulvt hvt}
set tech(vt_pattern,svt)  "*svt*"
set tech(vt_pattern,lvt)  "*lvt*"
set tech(vt_pattern,ulvt) "*ulvt*"
set tech(vt_pattern,hvt)  "*hvt*"

# ── Library root ───────────────────────────────────────────────────────
set tech(lib_root) "/tmp/test_libs/tsmc_7nm"
set _R "$tech(lib_root)"

# Additional lib paths (multiple roots — auto-read by library-manager generate)
set tech(lib_paths,stdcell) [list]
set tech(lib_paths,memory) [list]
set tech(lib_paths,io) [list]

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2: ACTIVE TRACK + VT FLAVORS
# ═══════════════════════════════════════════════════════════════════════════════

if {![info exists project(track_variant)] || $project(track_variant) eq ""} {
    puts "ERROR: project(track_variant) not set. Define it in your project_config.tcl"
    puts "       Technology: $tech(process) | Available tracks: $tech(tracks_available)"
    exit 1
}
if {[lsearch -exact $tech(tracks_available) $project(track_variant)] == -1} {
    puts "ERROR: Invalid track '$project(track_variant)' for $tech(process)"
    puts "       Available tracks: $tech(tracks_available)"
    exit 1
}
set tech(track) $project(track_variant)

set _vt_load $tech(vt_variants_available)
if {[info exists project(vt_flavors)] && $project(vt_flavors) ne ""} {
    set _vt_load $project(vt_flavors)
}
set tech(vt_flavors_loaded) $_vt_load

puts "INFO: $tech(process) active track: $tech(track), VT flavors: $_vt_load"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3: LIBRARY SETS (sourced from generated lib_config.tcl)
# Generated by: cbflow flow library-manager generate --lib-root <path> --tech tsmc_7nm
# Contains: NDM, DB, LEF, lib_nom, per-corner timing — fully resolved paths
# ═══════════════════════════════════════════════════════════════════════════════

set tech(lef_tech) "$_R/Back_End/lef/tsmc7nm_tech.lef"

if {[info exists project(lib_config_version)] && $project(lib_config_version) ne ""} {
    set _lib_config "$_tech_dir/lib_config_$project(lib_config_version).tcl"
} else {
    set _lib_config "$_tech_dir/lib_config.tcl"
}
if {[file exists $_lib_config]} {
    source $_lib_config
} else {
    puts "WARNING: lib_config not found: $_lib_config"
    puts "         Run: cbflow flow library-manager generate --lib-root <lib_path> --tech tsmc_7nm"
}

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4: PARASITIC EXTRACTION (shared — same for all tracks)
# ═══════════════════════════════════════════════════════════════════════════════

set tech(tluplus_map) "$_R/Back_End/rcx/tsmc7nm_tf_itf_tluplus.map"

set tech(rcx,rc_max,tluplus)   "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmax.tluplus"
set tech(rcx,rc_max,nxtgrd)    "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmax.nxtgrd"
set tech(rcx,rc_max,qrc)       "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmax.qrcTechFile"

set tech(rcx,rc_typ,tluplus)   "$_R/Back_End/rcx/tsmc7nm_1p12m_Ctyp.tluplus"
set tech(rcx,rc_typ,nxtgrd)    "$_R/Back_End/rcx/tsmc7nm_1p12m_Ctyp.nxtgrd"
set tech(rcx,rc_typ,qrc)       "$_R/Back_End/rcx/tsmc7nm_1p12m_Ctyp.qrcTechFile"

set tech(rcx,rc_min,tluplus)   "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmin.tluplus"
set tech(rcx,rc_min,nxtgrd)    "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmin.nxtgrd"
set tech(rcx,rc_min,qrc)       "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmin.qrcTechFile"

set tech(rcx,rc_max_cworst,tluplus) "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmax.tluplus"
set tech(rcx,rc_max_cworst,nxtgrd)  "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmax.nxtgrd"
set tech(rcx,rc_max_cworst,qrc)     "$_R/Back_End/rcx/tsmc7nm_1p12m_Cmax.qrcTechFile"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 5: PHYSICAL CELLS (per track — site, fillers, CTS, tap, endcap)
# ═══════════════════════════════════════════════════════════════════════════════

# ── 6T Physical ──
set tech(6T,site)           "TSMC_N7_SC6T"
set tech(6T,cell_height)    "0.270"
set tech(6T,site_width)     "0.054"
set tech(6T,fillers)        "TSMC_N7_SC6T_FILL1 TSMC_N7_SC6T_FILL2 TSMC_N7_SC6T_FILL4 TSMC_N7_SC6T_FILL8"
set tech(6T,well_tap)       "TSMC_N7_SC6T_FILLTIE1"
set tech(6T,endcap)         "TSMC_N7_SC6T_ENDCAP1"
set tech(6T,decap)          "TSMC_N7_SC6T_DCAP4 TSMC_N7_SC6T_DCAP8"
set tech(6T,clock_buffers)  "tcbn07bwp6tsvt_CKBUF4 tcbn07bwp6tsvt_CKBUF8"
set tech(6T,clock_inverters) "tcbn07bwp6tsvt_CKINV4"
set tech(6T,hold_buffers)   "tcbn07bwp6tsvt_BUFFD1 tcbn07bwp6tsvt_BUFFD2 tcbn07bwp6tsvt_BUFFD4"
set tech(6T,delay_cells)    "tcbn07bwp6tsvt_DEL1 tcbn07bwp6tsvt_DEL2 tcbn07bwp6tsvt_DEL4"
set tech(6T,icg_cells)      "tcbn07bwp6tsvt_CKLNQD1 tcbn07bwp6tsvt_CKLNQD2 tcbn07bwp6tsvt_CKLNQD4"
set tech(6T,power_switch)   "tcbn07bwp6tsvt_HDRDWN1 tcbn07bwp6tsvt_HDRDWN2 tcbn07bwp6tsvt_HDRDWN4"
set tech(6T,isolation)      "tcbn07bwp6tsvt_ISOLAND1 tcbn07bwp6tsvt_ISOLOR1 tcbn07bwp6tsvt_ISOLAND2 tcbn07bwp6tsvt_ISOLOR2"
set tech(6T,level_shifter)  "tcbn07bwp6tsvt_LSDOWN1 tcbn07bwp6tsvt_LSUP1 tcbn07bwp6tsvt_LSDOWN2 tcbn07bwp6tsvt_LSUP2"
set tech(6T,tie_cells)      "tcbn07bwp6tsvt_TIEHI tcbn07bwp6tsvt_TIELO"
set tech(6T,dont_use)       "*D0BWP6T* *OPTHOLD* *DEL*"

# ── 7.5T Physical ──
set tech(7.5T,site)           "TSMC_N7_SC7P5T"
set tech(7.5T,cell_height)    "0.338"
set tech(7.5T,site_width)     "0.054"
set tech(7.5T,fillers)        "TSMC_N7_SC7P5T_FILL1 TSMC_N7_SC7P5T_FILL2 TSMC_N7_SC7P5T_FILL4 TSMC_N7_SC7P5T_FILL8"
set tech(7.5T,well_tap)       "TSMC_N7_SC7P5T_FILLTIE1"
set tech(7.5T,endcap)         "TSMC_N7_SC7P5T_ENDCAP1"
set tech(7.5T,decap)          "TSMC_N7_SC7P5T_DCAP4 TSMC_N7_SC7P5T_DCAP8"
set tech(7.5T,clock_buffers)  "tcbn07bwp7p5tsvt_CKBUF4 tcbn07bwp7p5tsvt_CKBUF8"
set tech(7.5T,clock_inverters) "tcbn07bwp7p5tsvt_CKINV4"
set tech(7.5T,hold_buffers)   "tcbn07bwp7p5tsvt_BUFFD1 tcbn07bwp7p5tsvt_BUFFD2 tcbn07bwp7p5tsvt_BUFFD4"
set tech(7.5T,delay_cells)    "tcbn07bwp7p5tsvt_DEL1 tcbn07bwp7p5tsvt_DEL2 tcbn07bwp7p5tsvt_DEL4"
set tech(7.5T,icg_cells)      "tcbn07bwp7p5tsvt_CKLNQD1 tcbn07bwp7p5tsvt_CKLNQD2 tcbn07bwp7p5tsvt_CKLNQD4"
set tech(7.5T,power_switch)   "tcbn07bwp7p5tsvt_HDRDWN1 tcbn07bwp7p5tsvt_HDRDWN2 tcbn07bwp7p5tsvt_HDRDWN4"
set tech(7.5T,isolation)      "tcbn07bwp7p5tsvt_ISOLAND1 tcbn07bwp7p5tsvt_ISOLOR1 tcbn07bwp7p5tsvt_ISOLAND2 tcbn07bwp7p5tsvt_ISOLOR2"
set tech(7.5T,level_shifter)  "tcbn07bwp7p5tsvt_LSDOWN1 tcbn07bwp7p5tsvt_LSUP1 tcbn07bwp7p5tsvt_LSDOWN2 tcbn07bwp7p5tsvt_LSUP2"
set tech(7.5T,tie_cells)      "tcbn07bwp7p5tsvt_TIEHI tcbn07bwp7p5tsvt_TIELO"
set tech(7.5T,dont_use)       "*D0BWP7P5T* *OPTHOLD* *DEL*"

# ── 9T Physical ──
set tech(9T,site)           "TSMC_N7_SC9T"
set tech(9T,cell_height)    "0.405"
set tech(9T,site_width)     "0.054"
set tech(9T,fillers)        "TSMC_N7_SC9T_FILL1 TSMC_N7_SC9T_FILL2 TSMC_N7_SC9T_FILL4 TSMC_N7_SC9T_FILL8 TSMC_N7_SC9T_FILL16"
set tech(9T,well_tap)       "TSMC_N7_SC9T_FILLTIE1"
set tech(9T,endcap)         "TSMC_N7_SC9T_ENDCAP1"
set tech(9T,decap)          "TSMC_N7_SC9T_DCAP4 TSMC_N7_SC9T_DCAP8"
set tech(9T,clock_buffers)  "tcbn07bwp9tsvt_CKBUF4 tcbn07bwp9tsvt_CKBUF8"
set tech(9T,clock_inverters) "tcbn07bwp9tsvt_CKINV4"
set tech(9T,hold_buffers)   "tcbn07bwp9tsvt_BUFFD1 tcbn07bwp9tsvt_BUFFD2 tcbn07bwp9tsvt_BUFFD4"
set tech(9T,delay_cells)    "tcbn07bwp9tsvt_DEL1 tcbn07bwp9tsvt_DEL2 tcbn07bwp9tsvt_DEL4"
set tech(9T,icg_cells)      "tcbn07bwp9tsvt_CKLNQD1 tcbn07bwp9tsvt_CKLNQD2 tcbn07bwp9tsvt_CKLNQD4"
set tech(9T,power_switch)   "tcbn07bwp9tsvt_HDRDWN1 tcbn07bwp9tsvt_HDRDWN2 tcbn07bwp9tsvt_HDRDWN4"
set tech(9T,isolation)      "tcbn07bwp9tsvt_ISOLAND1 tcbn07bwp9tsvt_ISOLOR1 tcbn07bwp9tsvt_ISOLAND2 tcbn07bwp9tsvt_ISOLOR2"
set tech(9T,level_shifter)  "tcbn07bwp9tsvt_LSDOWN1 tcbn07bwp9tsvt_LSUP1 tcbn07bwp9tsvt_LSDOWN2 tcbn07bwp9tsvt_LSUP2"
set tech(9T,tie_cells)      "tcbn07bwp9tsvt_TIEHI tcbn07bwp9tsvt_TIELO"
set tech(9T,dont_use)       "*D0BWP9T* *OPTHOLD* *DEL*"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 6: DESIGN RULES & ROUTING
# ═══════════════════════════════════════════════════════════════════════════════

set tech(min_routing_layer) "M1"
set tech(max_routing_layer) "M11"
set tech(clock_routing_layer_min) "M4"
set tech(clock_routing_layer_max) "M9"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 7: SIGNOFF, DRC & GDS
# ═══════════════════════════════════════════════════════════════════════════════

set tech(gds_layer_map_file)        "$_R/Back_End/layermap/tsmc7nm_layermap.map"
set tech(antenna_rule_file)         "$_R/Back_End/antenna/tsmc7nm_antenna.rules"
set tech(lib_cell_purpose_file)     ""
set tech(filler_sidefile)           ""
set tech(signal_em_constraint_file) ""
set tech(signal_em_constraint_format) "sigem"
set tech(stream_files_for_merge)    ""

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 8: BACKWARD COMPATIBILITY — old variable names -> new
# ═══════════════════════════════════════════════════════════════════════════════

set _trk $tech(track)
if {[info exists tech(${_trk},ndm)] && [llength $tech(${_trk},ndm)] > 0} {
    set tech(ndm,standard_cells) [lindex $tech(${_trk},ndm) 0]
}
if {[info exists tech(${_trk},lef)] && [llength $tech(${_trk},lef)] > 0} {
    set tech(lef,standard_cells) [lindex $tech(${_trk},lef) 0]
}
set tech(library,root_path)    $tech(lib_root)
set tech(library,stdcell_path) "$tech(lib_root)/Front_End/timing/stdcell"
set tech(library,memory_path)  "$tech(lib_root)/Front_End/timing/memory"
set tech(library,io_path)      "$tech(lib_root)/Front_End/timing/io"

set tech(lef,technology) $tech(lef_tech)

if {[info exists tech(${_trk},lib_nom)]} {
    set tech(lib,timing) $tech(${_trk},lib_nom)
}

if {[info exists tech(${_trk},decap)]} {
    set tech(decap_cells) $tech(${_trk},decap)
}

puts "INFO: $tech(process) tech config loaded — track=$tech(track), VT=$tech(vt_flavors_loaded), metal=$tech(metal_stack), libs=[expr {[info exists tech(${_trk},ndm)] ? [llength $tech(${_trk},ndm)] : 0}] NDMs"
