#!/usr/bin/env tclsh
#===============================================================================
# CBFlow {{FLOW_NAME}} Makefile Generator
# Generated by: cbflow flow scaffold
# Version: 1.0.0
#===============================================================================

namespace eval ::CBFlow::Generation::{{FLOW_NAME}} {

    proc generate {output_file} {
        set flow_type "{{FLOW_NAME}}"
        set flow_lower [string tolower $flow_type]

        # Use common generator infrastructure
        if {[namespace exists ::CBFlow::Generation::Common]} {
            ::CBFlow::Generation::Common::generate_standard_makefile $flow_type $output_file
        } else {
            puts "ERROR: Common generation infrastructure not available"
            return 0
        }

        return 1
    }
}
