#!/usr/bin/env tclsh
#===============================================================================
# CBFlow {{FLOW_NAME}} Flow Node Configuration
# Generated by: cbflow flow scaffold
# Version: 1.0.0
#===============================================================================

array set {{FLOW_NAME_LOWER}} {
    stages {inputs1 run1 validate1 export_data1 release_data1}

    tool,vendor "{{VENDOR}}"
    tool,name "{{TOOL}}"
    tool,version "v1.0.0"
    tool,args "-batch -no_gui"

    supported_tools {{{TOOL}}}
    default_tool "{{TOOL}}"

    subnodes,inputs1 {setup validate finish}
    subnodes,run1 {setup run validate finish}
    subnodes,validate1 {setup run finish}
    subnodes,export_data1 {setup run finish}
    subnodes,release_data1 {setup run finish}

    dependencies,inputs1 {}
    dependencies,run1 {inputs1}
    dependencies,validate1 {run1}
    dependencies,export_data1 {validate1}
    dependencies,release_data1 {export_data1}

    subnode_dependencies,inputs1,validate {setup}
    subnode_dependencies,inputs1,finish {validate}
    subnode_dependencies,run1,run {setup}
    subnode_dependencies,run1,validate {run}
    subnode_dependencies,run1,finish {validate}

    runtime,timeout,inputs1 3600
    runtime,timeout,run1 14400
    runtime,timeout,validate1 3600
    runtime,timeout,export_data1 1800
    runtime,timeout,release_data1 1800
}
