#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# CBFlow Node Management - Persistence
# Description: Save and load runtime configuration
# ═══════════════════════════════════════════════════════════════════════════════

namespace eval ::CBFlow::NodeManagement::Persistence {
}

# ┌─ Save Configuration ─────────────────────────────────────────────────────────┐

proc ::CBFlow::NodeManagement::Persistence::save_flow_config {} {
    global flow

    set current_flow_type [::CBFlow::NodeManagement::get_current_flow_type]
    set flow_var [string tolower $current_flow_type]

    if {![info exists ::env(CBFLOW_RUN_DIR)]} {
        CBFLOW_ERROR "CBFLOW_RUN_DIR environment variable not set"
        return false
    }

    set setup_dir "$::env(CBFLOW_RUN_DIR)/setup"
    if {![file exists $setup_dir]} {
        file mkdir $setup_dir
    }

    set runtime_config "$setup_dir/runtime_flow_config.tcl"

    upvar #0 $flow_var flow_array

    if {![array exists flow_array]} {
        CBFLOW_WARNING "No flow configuration to save"
        return false
    }

    # Only save custom node data (stages,* and branch_keys,*), not base config
    set custom_data {}
    foreach {key value} [array get flow_array] {
        if {[string match "stages,*" $key] || [string match "branch_keys,*" $key]} {
            lappend custom_data $key $value
        }
    }

    set fd [open $runtime_config "w"]
    puts $fd "# Runtime Flow Configuration - Custom Nodes Only"
    puts $fd "# Generated by ::CBFlow::NodeManagement on [clock format [clock seconds]]"
    puts $fd "# This configuration is local to this run directory"
    puts $fd "# Flow type: $current_flow_type"
    puts $fd "# NOTE: This file only contains custom node configurations."
    puts $fd "# Base flow configuration comes from the node_configs/*.tcl files."
    puts $fd ""

    if {[llength $custom_data] > 0} {
        puts $fd "# Custom node and branch configuration for $current_flow_type"
        puts $fd "array set $flow_var {"
        foreach {key value} $custom_data {
            puts $fd "    [list $key] [list $value]"
        }
        puts $fd "}"
    } else {
        puts $fd "# No custom nodes defined"
    }
    puts $fd ""

    close $fd

    CBFLOW_INFO "Configuration saved to: $runtime_config"
    return true
}

# ┌─ Load Configuration ─────────────────────────────────────────────────────────┐

proc ::CBFlow::NodeManagement::Persistence::load_runtime_config {} {
    if {![info exists ::env(CBFLOW_RUN_DIR)]} {
        CBFLOW_ERROR "CBFLOW_RUN_DIR environment variable not set"
        return false
    }

    set runtime_config "$::env(CBFLOW_RUN_DIR)/setup/runtime_flow_config.tcl"

    if {[file exists $runtime_config]} {
        if {[catch {source $runtime_config} error]} {
            CBFLOW_ERROR "Failed to load runtime configuration: $error"
            return false
        }
        CBFLOW_DEBUG "Runtime configuration loaded from: $runtime_config"
        return true
    }

    CBFLOW_DEBUG "No runtime configuration file found"
    return false
}

proc ::CBFlow::NodeManagement::Persistence::load_runtime_config_for_flow {flow_type} {
    set flow_type_lower [string tolower $flow_type]

    if {![info exists ::env(CBFLOW_RUN_DIR)]} {
        return false
    }

    set runtime_config "$::env(CBFLOW_RUN_DIR)/setup/runtime_flow_config.tcl"

    if {[file exists $runtime_config]} {
        if {[catch {uplevel #0 source $runtime_config} error] == 0} {
            return true
        }
    }

    return false
}

# ┌─ Convenience Alias ──────────────────────────────────────────────────────────┐

proc ::CBFlow::NodeManagement::save_flow_config {} {
    return [::CBFlow::NodeManagement::Persistence::save_flow_config]
}
