#!/usr/bin/env tclsh
# CBFlow STA MMMC_SETUP Subnode Handler - Synopsys PT
if {$argc < 1} { puts "ERROR: Missing subnode argument"; exit 1 }
set subnode_name [lindex $argv 0]
set run_dir [expr {$argc > 1 ? [lindex $argv 1] : [pwd]}]
set node_name [expr {$argc > 2 ? [lindex $argv 2] : ""}]
if {[file exists "$run_dir/.run.cbflow.tcl"]} { source "$run_dir/.run.cbflow.tcl" } else { puts "ERROR: .run.cbflow.tcl not found"; exit 1 }
source "$::env(SCRIPTS_ROOT)/utilities/$::env(UTILITIES_VERSION)/error_utils.tcl"
set flow_config "$::env(CONFIG_ROOT)/flow/$::env(FLOW_CONFIG_VERSION)/flow_config.tcl"
if {[file exists $flow_config]} { source $flow_config }
set node_config "$::env(CONFIG_ROOT)/flow/$::env(FLOW_CONFIG_VERSION)/node_configs/STA_config.tcl"
if {[file exists $node_config]} { source $node_config }
if {[file exists "$run_dir/setup/user_config.tcl"]} { source "$run_dir/setup/user_config.tcl" }
# Source tool launch config (module load, tool shell, bsub, xterm)
set _launch_config "$::env(CONFIG_ROOT)/flow/$::env(FLOW_CONFIG_VERSION)/tool_launch_config.tcl"
if {[file exists $_launch_config]} { source $_launch_config }
set ::flow_type "STA"
set stage_name "mmmc_setup"
if {$node_name eq ""} { set node_name $stage_name }
set _tool_ver [expr {[info exists ::env(PT_VERSION)] ? $::env(PT_VERSION) : {v1.0.0}}]
set cmd_file "$::env(FLOW_DIR)/cmds/STA/synopsys/pt/$_tool_ver/mmmc_setup_pt.tcl"
set test_mode false
if {[info exists flow(test_mode)] && $flow(test_mode) eq "true"} { set test_mode true }
switch $subnode_name {
    "setup" {
        puts "INFO: $stage_name setup..."
        file mkdir "$run_dir/work/$::flow_type/$node_name/run"
        file mkdir "$run_dir/work/$::flow_type/$node_name/setup"
        puts "INFO: $stage_name setup completed"
    }
    "load_config" {
        puts "INFO: $stage_name load_config..."
        set mmmc_config_file "$::env(CONFIG_ROOT)/flow/$::env(FLOW_CONFIG_VERSION)/mmmc_config.tcl"
        if {[file exists $mmmc_config_file]} {
            source $mmmc_config_file
            puts "INFO: MMMC configuration loaded from $mmmc_config_file"
        } else {
            puts "ERROR: MMMC config not found: $mmmc_config_file"
            exit 1
        }
        puts "INFO: $stage_name load_config completed"
    }
    "resolve_scenarios" {
        puts "INFO: $stage_name resolve_scenarios..."
        # MMMC setup ALWAYS runs (even in test mode) because it generates
        # directories, active_scenarios.tcl, and dynamic .make/ files.
        # No EDA tool is invoked -- this is pure config/file generation.

        # Source MMMC config to get scenarios
        set mmmc_config_file "$::env(CONFIG_ROOT)/flow/$::env(FLOW_CONFIG_VERSION)/mmmc_config.tcl"
        if {[file exists $mmmc_config_file]} { source $mmmc_config_file }

        # Determine active scenario set
        set scenario_set "signoff"
        if {[info exists sta(mmmc,scenario_set)]} { set scenario_set $sta(mmmc,scenario_set) }
        set active_scenarios [get_scenario_set $scenario_set]
        puts "INFO: Scenario set: $scenario_set ([llength $active_scenarios] scenarios)"

        # Write active_scenarios.tcl
        set scenarios_dir "$run_dir/work/$::flow_type/$node_name/run"
        file mkdir $scenarios_dir
        set scenarios_file "$scenarios_dir/active_scenarios.tcl"
        set fh [open $scenarios_file "w"]
        puts $fh "# Auto-generated by CBFlow mmmc_setup - active MMMC scenarios"
        puts $fh "# Scenario set: $scenario_set"
        puts $fh "# Generated: [clock format [clock seconds]]"
        puts $fh ""
        puts $fh "set mmmc_active_scenario_set \"$scenario_set\""
        puts $fh "set mmmc_active_scenarios \{"
        foreach s $active_scenarios { puts $fh "    $s" }
        puts $fh "\}"
        puts $fh ""
        puts $fh "puts \"INFO: Loaded [llength $active_scenarios] active scenarios from set: $scenario_set\""
        close $fh
        puts "INFO: Written: $scenarios_file"

        # Create per-scenario work directories
        file mkdir "$run_dir/reports/sta"
        file mkdir "$run_dir/results/sta"
        foreach s $active_scenarios {
            file mkdir "$run_dir/work/$::flow_type/timing/$s"
            puts "INFO:   Created work dir for scenario: $s"
        }

        # Generate dynamic .make/ files for per-scenario timing targets
        set make_dir "$run_dir/.make"
        file mkdir $make_dir

        # Generate individual per-scenario .mk files
        foreach s $active_scenarios {
            set mk_file "$make_dir/timing_${s}.mk"
            set fh [open $mk_file "w"]
            puts $fh "# Auto-generated timing target for scenario: $s"
            puts $fh "TIMING_[string toupper [string map {. _ - _} $s]]_STAMP = \$(STAMP_DIR)/timing_${s}.stamp"
            puts $fh ""
            puts $fh "\$(STAMP_DIR)/timing_${s}.stamp: \$(STAMP_DIR)/extraction1.stamp"
            puts $fh "\t@echo \"Running timing for scenario: $s...\""
            puts $fh "\t@mkdir -p \$(STAMP_DIR)"
            puts $fh "\t@tclsh \"\$(FLOW_DIR)/cmds/STA/synopsys/pt/\$(PT_VERSION)/timing_scenario_handler.tcl\" $s \"\$(PWD)\""
            puts $fh "\t@echo \"done timing $s completed\""
            puts $fh "\t@touch \$@"
            close $fh
            puts "INFO:   Generated: timing_${s}.mk"
        }

        # Generate timing_dynamic.mk that aggregates all scenario targets
        set dyn_file "$make_dir/timing_dynamic.mk"
        set fh [open $dyn_file "w"]
        puts $fh "# Auto-generated dynamic timing targets by CBFlow mmmc_setup"
        puts $fh "# Scenario set: $scenario_set ([llength $active_scenarios] scenarios)"
        puts $fh "# Use 'make -j' for parallel scenario execution"
        puts $fh ""
        puts $fh "TIMING_SCENARIOS = [join $active_scenarios { }]"
        puts $fh ""
        # Include per-scenario .mk files
        foreach s $active_scenarios {
            puts $fh "-include .make/timing_${s}.mk"
        }
        puts $fh ""
        puts $fh ".PHONY: timing1"
        puts $fh "timing1: \$(foreach s,\$(TIMING_SCENARIOS),\$(STAMP_DIR)/timing_\$(s).stamp)"
        puts $fh "\t@echo \"done timing1 stage completed ([llength $active_scenarios] scenarios)\""
        puts $fh "\t@touch \$(STAMP_DIR)/timing1.stamp"
        close $fh
        puts "INFO:   Generated: timing_dynamic.mk (aggregates [llength $active_scenarios] scenario targets)"

        puts "INFO: $stage_name resolve_scenarios completed"
    }
    "validate" {
        puts "INFO: $stage_name validate..."
        # Verify active_scenarios.tcl was generated (always, even in test mode)
        set scenarios_file "$run_dir/work/$::flow_type/$node_name/run/active_scenarios.tcl"
        if {[file exists $scenarios_file]} {
            puts "INFO: Validated: $scenarios_file exists"
            source $scenarios_file
            puts "INFO: Active scenarios: [llength $mmmc_active_scenarios]"
        } else {
            puts "ERROR: active_scenarios.tcl not found at $scenarios_file"
            exit 1
        }
        # Verify dynamic .make/ files were generated
        set dyn_mk "$run_dir/.make/timing_dynamic.mk"
        if {[file exists $dyn_mk]} {
            puts "INFO: Validated: timing_dynamic.mk exists"
        } else {
            puts "WARNING: timing_dynamic.mk not found - timing1 will use fallback"
        }
        puts "INFO: $stage_name validate completed"
    }
    "finish" {
        puts "INFO: $stage_name finish..."
        set ff "$run_dir/work/$::flow_type/$node_name/run/${stage_name}_finish.timestamp"
        file mkdir [file dirname $ff]
        set fh [open $ff "w"]; puts $fh "Completed: [clock format [clock seconds]]"; close $fh
        puts "INFO: $stage_name finish completed"
    }
    default { puts "ERROR: Unknown subnode: $subnode_name"; exit 1 }
}
