#!/usr/bin/env tclsh
# ==============================================================================
# FP init_design — Cadence Innovus
# Description: Generate design.globals, source it, run init_design, load
#              floorplan, connect PG nets, activate MMMC scenarios.
#              Follows Cadence Foundation Flow pattern.
# ==============================================================================

# ── Bootstrap ─────────────────────────────────────────────────────────────────
set run_dir $::env(CBFLOW_RUN_DIR)
source "$run_dir/.run.cbflow.tcl"
source "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/utils.tcl"

set FLOW_TYPE "FP"
set STAGE_NAME "init_design"
set NODE_NAME "init_design1"

source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/config.tcl"
source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/setup.tcl"
setup_dirs $run_dir $FLOW_TYPE $NODE_NAME

handle_info "Starting CBflow FP init_design for Innovus"

# ==============================================================================
# flow_proc: generate_globals
# Description: Write design.globals file (Innovus init_* variables)
#   Reference: Cadence Foundation Flow — DATA/leon.globals
# ==============================================================================
flow_proc generate_globals {
    global fp project tech flow run_dir FLOW_TYPE NODE_NAME

    handle_info "Generating design.globals..."

    set design_name $flow(design_name)
    set globals_file "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/design.globals"

    set gf [open $globals_file w]
    puts $gf "# ============================================================================"
    puts $gf "# design.globals — Auto-generated by CBflow FP init_design"
    puts $gf "# Design: $design_name"
    puts $gf "# ============================================================================"
    puts $gf ""

    # ── Verilog netlist (mandatory) ──
    if {![info exists fp(input,netlist)] || $fp(input,netlist) eq ""} {
        handle_error "fp(input,netlist) not set — gate-level netlist required"
        exit 1
    }
    puts $gf "set init_verilog {$fp(input,netlist)}"

    # ── Top cell ──
    set top_cell $design_name
    if {[info exists project(top_module)] && $project(top_module) ne ""} {
        set top_cell $project(top_module)
    }
    puts $gf "set init_design_settop 1"
    puts $gf "set init_top_cell {$top_cell}"

    # ── LEF files ──
    set lef_list [list]

    # Tech LEF (metal_stack × track)
    set _trk $project(track_variant)
    set _ms $project(metal_stack)
    lappend lef_list $tech(${_ms},${_trk},lef_tech)

    # Cell LEFs per track
    if {[info exists tech(${_trk},lef)]} {
        foreach lef $tech(${_trk},lef) {
            if {$lef ne ""} { lappend lef_list $lef }
        }
    }

    # Additional LEFs from user (macros, hard IPs)
    if {[info exists fp(input,additional_lefs)]} {
        foreach lef $fp(input,additional_lefs) {
            if {$lef ne ""} { lappend lef_list $lef }
        }
    }

    if {[llength $lef_list] == 0} {
        handle_error "No LEF files — check tech(<ms>,<track>,lef_tech) and tech(<track>,lef)"
        exit 1
    }
    puts $gf "set init_lef_file {[join $lef_list { }]}"

    # ── Power/Ground nets ──
    if {![info exists project(power,vdd_net)] || ![info exists project(power,vss_net)]} {
        handle_error "project(power,vdd_net) and project(power,vss_net) must be set"
        exit 1
    }
    puts $gf "set init_pwr_net {$project(power,vdd_net)}"
    puts $gf "set init_gnd_net {$project(power,vss_net)}"

    # ── MMMC view definition file ──
    set vd_file ""
    if {[info exists fp(input,mmmc_file)] && $fp(input,mmmc_file) ne ""} {
        set vd_file $fp(input,mmmc_file)
    } else {
        set vd_file "$::env(FLOW_DIR)/config/project/$project(name)/$project(cbflow_release)/mmmc_view_definition.tcl"
    }
    if {$vd_file ne "" && [file exists $vd_file]} {
        puts $gf "set init_mmmc_file {$vd_file}"
    } else {
        handle_warning "MMMC view definition not found: $vd_file"
        handle_warning "  Generate with: cbflow flow mmmc-manager generate --project $project(name)"
    }

    # ── QRC tech file (optional) ──
    foreach _fmt {qrc nxtgrd} {
        set _key "rcx,rc_max,$_fmt"
        if {[info exists tech($_key)] && $tech($_key) ne "" && [file exists $tech($_key)]} {
            puts $gf "set conf_qxconf_file {NULL}"
            puts $gf "set conf_qxlib_file {NULL}"
            break
        }
    }

    puts $gf ""
    close $gf

    handle_info "  Generated: $globals_file"
    handle_info "  Netlist:   $fp(input,netlist)"
    handle_info "  LEFs:      [llength $lef_list] files"
    handle_info "  Power:     $project(power,vdd_net) / $project(power,vss_net)"
    handle_info "  Top cell:  $top_cell"
    if {$vd_file ne ""} {
        handle_info "  MMMC:      [file tail $vd_file]"
    }

    return $globals_file
}

# ==============================================================================
# flow_proc: run_init_design
# Description: Source design.globals + call init_design (Cadence Foundation Flow)
# ==============================================================================
flow_proc run_init_design {
    global run_dir FLOW_TYPE NODE_NAME

    set globals_file "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/design.globals"

    if {![file exists $globals_file]} {
        handle_error "design.globals not found — run generate_globals first"
        exit 1
    }

    handle_info "Sourcing design.globals..."
    source $globals_file

    handle_info "Running init_design..."
    init_design

    handle_info "init_design completed"
}

# ==============================================================================
# flow_proc: load_floorplan
# Description: Load floorplan file (.fp) if provided — macro placement, rows,
#              tracks, PG nets. Reference: loadFPlan DATA/leon.power.fp
# ==============================================================================
flow_proc load_floorplan {
    global fp

    if {[info exists fp(input,floorplan_file)] && $fp(input,floorplan_file) ne ""} {
        if {[file exists $fp(input,floorplan_file)]} {
            handle_info "Loading floorplan: [file tail $fp(input,floorplan_file)]"
            loadFPlan $fp(input,floorplan_file)
        } else {
            handle_error "Floorplan file not found: $fp(input,floorplan_file)"
            exit 1
        }
    } elseif {[info exists fp(input,def_file)] && $fp(input,def_file) ne ""} {
        if {[file exists $fp(input,def_file)]} {
            handle_info "Reading DEF: [file tail $fp(input,def_file)]"
            defIn $fp(input,def_file)
        } else {
            handle_error "DEF file not found: $fp(input,def_file)"
            exit 1
        }
    } else {
        handle_info "No floorplan/DEF — starting with empty floorplan"
    }
}

# ==============================================================================
# flow_proc: setup_power_intent
# Description: Read UPF, commit power intent
# ==============================================================================
flow_proc setup_power_intent {
    global fp

    if {[info exists fp(input,upf_file)] && $fp(input,upf_file) ne ""} {
        if {[file exists $fp(input,upf_file)]} {
            handle_info "Reading UPF: [file tail $fp(input,upf_file)]"
            read_power_intent -1801 $fp(input,upf_file)

            if {[info exists fp(input,upf_supplemental)] && [file exists $fp(input,upf_supplemental)]} {
                handle_info "Reading supplemental UPF: [file tail $fp(input,upf_supplemental)]"
                read_power_intent -1801 $fp(input,upf_supplemental)
            }

            commit_power_intent
            handle_info "Power intent committed"
        } else {
            handle_warning "UPF not found: $fp(input,upf_file)"
        }
    } else {
        handle_info "No UPF — single power domain"
    }
}

# ==============================================================================
# flow_proc: connect_global_nets
# Description: Connect PG pins after design initialization
# ==============================================================================
flow_proc connect_global_nets {
    global project fp

    set pwr $project(power,vdd_net)
    set gnd $project(power,vss_net)
    set pwr_pin $project(power,vdd_pin)
    set gnd_pin $project(power,vss_pin)

    handle_info "Connecting global nets: $pwr/$gnd"

    globalNetConnect $pwr -type pgpin -pin $pwr_pin -inst * -override
    globalNetConnect $gnd -type pgpin -pin $gnd_pin -inst * -override

    # Tie-high/tie-low
    if {[info exists fp(power,tie_high_pin)] && $fp(power,tie_high_pin) ne ""} {
        globalNetConnect $pwr -type tiehi -pin $fp(power,tie_high_pin) -inst * -override
    }
    if {[info exists fp(power,tie_low_pin)] && $fp(power,tie_low_pin) ne ""} {
        globalNetConnect $gnd -type tielo -pin $fp(power,tie_low_pin) -inst * -override
    }

    handle_info "Global nets connected"
}

# ==============================================================================
# flow_proc: set_design_mode
# Description: Set process node and multi-CPU usage
# ==============================================================================
flow_proc set_design_mode {
    global tech fp

    # Process node (mandatory)
    if {![info exists tech(node)] || $tech(node) eq ""} {
        handle_error "tech(node) not set"
        exit 1
    }
    set node_nm [string trimright $tech(node) "nm"]
    handle_info "Setting design mode: process $node_nm"
    setDesignMode -process $node_nm

    # Multi-CPU (mandatory)
    if {![info exists fp(common,cpu_count)] || $fp(common,cpu_count) eq ""} {
        handle_error "fp(common,cpu_count) not set"
        exit 1
    }
    handle_info "Setting CPU usage: $fp(common,cpu_count)"
    setMultiCpuUsage -localCpu $fp(common,cpu_count)

    # Analysis mode (from config)
    if {![info exists fp(common,analysis_type)] || $fp(common,analysis_type) eq ""} {
        handle_error "fp(common,analysis_type) not set (e.g., onChipVariation, single)"
        exit 1
    }
    if {![info exists fp(common,cppr)] || $fp(common,cppr) eq ""} {
        handle_error "fp(common,cppr) not set (e.g., both, setup, hold, none)"
        exit 1
    }
    handle_info "Analysis mode: $fp(common,analysis_type) cppr=$fp(common,cppr)"
    setAnalysisMode -analysisType $fp(common,analysis_type) -cppr $fp(common,cppr)

    handle_info "Design mode set"
}

# ==============================================================================
# flow_proc: activate_node_scenarios
# Description: Activate only this node's MMMC scenarios
# ==============================================================================
flow_proc activate_node_scenarios {
    global mmmc STAGE_NAME

    if {![info exists mmmc($STAGE_NAME)]} {
        handle_info "No node-specific scenarios for $STAGE_NAME — all views remain active"
        return
    }

    handle_info "Activating scenarios for: $STAGE_NAME"

    array set _nd $mmmc($STAGE_NAME)
    set _setup [expr {[info exists _nd(setup)] ? $_nd(setup) : {}}]
    set _hold  [expr {[info exists _nd(hold)]  ? $_nd(hold)  : {}}]

    handle_info "  Setup: $_setup"
    handle_info "  Hold:  $_hold"

    # Deactivate all, then activate node-specific
    set_analysis_view -setup {} -hold {}
    set_analysis_view -setup $_setup -hold $_hold

    handle_info "Active scenarios set"
}

# ==============================================================================
# flow_proc: save_design
# Description: Save Innovus database checkpoint
# ==============================================================================
flow_proc save_design {
    set _outputs "$::WORK_DIR/outputs"
    file mkdir $_outputs

    saveDesign "$_outputs/init_design.enc"
    handle_info "Design saved: $_outputs/init_design.enc"
}

# ==============================================================================
# flow_proc: generate_reports
# Description: Post-init design reports
# ==============================================================================
flow_proc generate_reports {
    handle_info "Generating init_design reports..."

    file mkdir "$::REPORTS_DIR"

    catch { reportDesign "$::REPORTS_DIR/design_summary.rpt" }
    catch { timeDesign -prePlace -outDir "$::REPORTS_DIR" -prefix init_design }
    catch { report_area -outfile "$::REPORTS_DIR/report_area.rpt" }
    catch { report_power -outfile "$::REPORTS_DIR/report_power.rpt" }
    catch { checkDesign -all -outfile "$::REPORTS_DIR/check_design.rpt" }

    handle_info "Reports: $::REPORTS_DIR/"
}

# ==============================================================================
# Source setup hooks (user overrides — applied AFTER flow_proc defs)
# ==============================================================================
foreach _hook [list \
    "$run_dir/setup/override_setup.tcl" \
    "$run_dir/setup/override_setup.init_design.tcl" \
] {
    if {[file exists $_hook]} {
        handle_info "Sourcing hook: [file tail $_hook]"
        source $_hook
    }
}

# ==============================================================================
# Execute — Cadence Foundation Flow sequence
#   1. Generate design.globals (LEFs, netlist, MMMC, power nets)
#   2. Source globals + init_design
#   3. Load floorplan (.fp or .def)
#   4. Power intent (UPF)
#   5. Connect global PG nets
#   6. Set design mode (process, OCV, CPU)
#   7. Activate node MMMC scenarios
#   8. Save checkpoint
#   9. Reports
# ==============================================================================
handle_info "================================================================"
handle_info "CBflow FP init_design — Innovus (Foundation Flow)"
handle_info "================================================================"

foreach step {
    generate_globals
    run_init_design
    load_floorplan
    setup_power_intent
    connect_global_nets
    set_design_mode
    activate_node_scenarios
    save_design
    generate_reports
} {
    handle_info "── $step ──"
    if {[catch {$step} err]} {
        handle_error "Step '$step' failed: $err"
        exit 1
    }
}

handle_info "FP init_design completed"
