#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# CBflow PNR — release_data Subnode Handler (Cadence Innovus)
# Subnodes: setup, run, validate, finish
# ═══════════════════════════════════════════════════════════════════════════════

source "$::env(SCRIPTS_ROOT)/utilities/$::env(UTILITIES_VERSION)/handler_common.tcl"
source "$::env(SCRIPTS_ROOT)/utilities/$::env(UTILITIES_VERSION)/launch_utils.tcl"

lassign [handler_parse_args $argv $argc] subnode_name run_dir node_name
handler_load_configs $run_dir "PNR"

set ::flow_type "PNR"
set stage_name "release_data"
if {$node_name eq ""} { set node_name "${stage_name}1" }

set _tool_ver [expr {[info exists ::env(INNOVUS_VERSION)] ? $::env(INNOVUS_VERSION) : "v1.0.0"}]
set cmd_file "$::env(FLOW_DIR)/cmds/PNR/cadence/innovus/$_tool_ver/release_data_handler.tcl"

set test_mode [handler_is_test_mode]

switch $subnode_name {
    "setup" {
        puts "INFO: $stage_name setup..."
        handler_setup $run_dir $::flow_type $node_name
        # Generate local command file (copy from PD/cmds, add header)
        set _gen_file "$run_dir/work/$::flow_type/$node_name/run/${node_name}.innovus.tcl"
        if {[file exists $cmd_file]} {
            set _src_fh [open $cmd_file r]
            set _src_content [read $_src_fh]
            close $_src_fh
            set _gen_fh [open $_gen_file w]
            puts $_gen_fh "# Generated by CBflow setup — copied from [file tail $cmd_file]"
            puts $_gen_fh "# Node: $node_name | Stage: $stage_name"
            puts $_gen_fh "# Sourceable in tool — all configs resolved via config.tcl"
            puts $_gen_fh ""
            puts $_gen_fh $_src_content
            close $_gen_fh
            puts "INFO: Command file: $_gen_file"
        }
        puts "INFO: $stage_name setup completed"
    }
    "run" {
        puts "INFO: $stage_name run..."
        set _gen_file "$run_dir/work/$::flow_type/$node_name/run/${node_name}.innovus.tcl"
        set _tool [expr {[info exists pnr(tool,name)] ? $pnr(tool,name) : "innovus"}]
        handler_run $run_dir $::flow_type $node_name $stage_name $_gen_file $test_mode $_tool
    }
    "validate" {
        puts "INFO: $stage_name validate..."
        handler_validate $run_dir $::flow_type $node_name $stage_name $test_mode
        puts "INFO: $stage_name validate completed"
    }
    "finish" {
        puts "INFO: $stage_name finish..."
        handler_finish $run_dir $::flow_type $node_name $stage_name
        puts "INFO: $stage_name finish completed"
    }
    default {
        puts "ERROR: Unknown subnode: $subnode_name"
        exit 1
    }
}
