#!/usr/bin/env tclsh
# =============================================================================
# AUTO-GENERATED by: cbflow flow library-manager generate
# Tech: gf_28nm | Generated: 2026-06-03 22:19
# Source: /tmp/test_libs/gf_28nm
# Tracks: 7T 9T | VTs: rvt lvt ulvt hvt
# Corners: 11
# DO NOT EDIT — regenerate with: cbflow flow library-manager generate
# =============================================================================

# ── NDM per track per VT ──
set tech(7T,rvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_rvt_c30.ndm"]
set tech(7T,lvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_lvt_c30.ndm"]
set tech(7T,ulvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_ulvt_c30.ndm"]
set tech(7T,hvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_hvt_c30.ndm"]
set tech(9T,rvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_rvt_c30.ndm"]
set tech(9T,lvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_lvt_c30.ndm"]
set tech(9T,ulvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_ulvt_c30.ndm"]
set tech(9T,hvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_hvt_c30.ndm"]

# ── NDM shared ──
set tech(ndm,memory) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sram28slpe_memory.ndm"]
set tech(ndm,io) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/io28slpe_io.ndm"]
set tech(ndm,analog) [list]

# ── NDM combined per track ──
set tech(7T,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_rvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_lvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_ulvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_hvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sram28slpe_memory.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/io28slpe_io.ndm"]
set tech(9T,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_rvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_lvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_ulvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_hvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sram28slpe_memory.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/io28slpe_io.ndm"]

# ── DB per track per VT ──
set tech(7T,rvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(7T,lvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(7T,ulvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(7T,hvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,rvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,lvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,ulvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,hvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]

# ── DB shared ──
set tech(db,memory) [list ]
set tech(db,io) [list ]

# ── DB combined per track ──
set tech(7T,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]

# ── lib_nom per track per VT ──

# ── lib_nom shared ──
set tech(lib_nom,memory) [list ]
set tech(lib_nom,io) [list ]

# ── lib_nom combined per track (from TT nominal: tt_0p90v_125c) ──
set tech(7T,lib_nom) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,lib_nom) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]

# ── LEF per track per VT ──
set tech(7T,rvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_rvt_c30.lef"]
set tech(7T,lvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_lvt_c30.lef"]
set tech(7T,ulvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_ulvt_c30.lef"]
set tech(7T,hvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_hvt_c30.lef"]
set tech(9T,rvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_rvt_c30.lef"]
set tech(9T,lvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_lvt_c30.lef"]
set tech(9T,ulvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_ulvt_c30.lef"]
set tech(9T,hvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_hvt_c30.lef"]

# ── LEF shared ──
set tech(lef,memory) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sram28slpe_memory.lef"]
set tech(lef,io) [list "/tmp/test_libs/gf_28nm/Back_End/lef/io28slpe_io.lef"]

# ── LEF combined per track ──
set tech(7T,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_rvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_lvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_ulvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_hvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sram28slpe_memory.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/io28slpe_io.lef"]
set tech(9T,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_rvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_lvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_ulvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_hvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sram28slpe_memory.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/io28slpe_io.lef"]

# ── Corners discovered ──
set tech(corners) {ff_1p00v_m40c ff_1p10v_125c ff_1p10v_25c ff_1p10v_m40c ss_0p80v_125c ss_0p80v_m40c ss_0p90v_125c ss_0p90v_m40c tt_0p90v_125c tt_0p90v_25c tt_0p90v_m40c}

# ── Timing libs per track per VT per corner ──
set tech(7T,rvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(7T,rvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,lvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,ulvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(7T,hvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz"]
set tech(9T,rvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,lvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,ulvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,hvt,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]

# ── Timing libs shared per corner (memory + IO) ──
set tech(lib,ff_1p00v_m40c,timing,memory) [list ]
set tech(lib,ff_1p00v_m40c,timing,io) [list ]
set tech(lib,ff_1p10v_125c,timing,memory) [list ]
set tech(lib,ff_1p10v_125c,timing,io) [list ]
set tech(lib,ff_1p10v_25c,timing,memory) [list "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ff_nominal_min_1p10v_25c.lib"]
set tech(lib,ff_1p10v_25c,timing,io) [list "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ff_nominal_min_1p10v_25c.lib"]
set tech(lib,ff_1p10v_m40c,timing,memory) [list "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ff_nominal_min_1p10v_m40c.lib"]
set tech(lib,ff_1p10v_m40c,timing,io) [list "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ff_nominal_min_1p10v_m40c.lib"]
set tech(lib,ss_0p80v_125c,timing,memory) [list ]
set tech(lib,ss_0p80v_125c,timing,io) [list ]
set tech(lib,ss_0p80v_m40c,timing,memory) [list ]
set tech(lib,ss_0p80v_m40c,timing,io) [list ]
set tech(lib,ss_0p90v_125c,timing,memory) [list "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ss_nominal_max_0p90v_125c.lib"]
set tech(lib,ss_0p90v_125c,timing,io) [list "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ss_nominal_max_0p90v_125c.lib"]
set tech(lib,ss_0p90v_m40c,timing,memory) [list "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ss_nominal_max_0p90v_m40c.lib"]
set tech(lib,ss_0p90v_m40c,timing,io) [list "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ss_nominal_max_0p90v_m40c.lib"]
set tech(lib,tt_0p90v_125c,timing,memory) [list ]
set tech(lib,tt_0p90v_125c,timing,io) [list ]
set tech(lib,tt_0p90v_25c,timing,memory) [list "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_tt_nominal_typ_0p90v_25c.lib"]
set tech(lib,tt_0p90v_25c,timing,io) [list "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_tt_nominal_typ_0p90v_25c.lib"]
set tech(lib,tt_0p90v_m40c,timing,memory) [list ]
set tech(lib,tt_0p90v_m40c,timing,io) [list ]

# ── Timing combined per track per corner ──
set tech(7T,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(7T,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(7T,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ff_nominal_min_1p10v_25c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ff_nominal_min_1p10v_25c.lib"]
set tech(7T,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ff_nominal_min_1p10v_m40c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ff_nominal_min_1p10v_m40c.lib"]
set tech(7T,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(7T,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(7T,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ss_nominal_max_0p90v_125c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ss_nominal_max_0p90v_125c.lib"]
set tech(7T,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ss_nominal_max_0p90v_m40c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ss_nominal_max_0p90v_m40c.lib"]
set tech(7T,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(7T,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_tt_nominal_typ_0p90v_25c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_tt_nominal_typ_0p90v_25c.lib"]
set tech(7T,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]
set tech(9T,lib,ff_1p00v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p00v_m40c.lib_ccs_tn.gz"]
set tech(9T,lib,ff_1p10v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_125c.lib_ccs_tn.gz"]
set tech(9T,lib,ff_1p10v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ff_nominal_min_1p10v_25c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ff_nominal_min_1p10v_25c.lib"]
set tech(9T,lib,ff_1p10v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ff_nominal_min_1p10v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ff_nominal_min_1p10v_m40c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ff_nominal_min_1p10v_m40c.lib"]
set tech(9T,lib,ss_0p80v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_125c.lib_ccs_tn.gz"]
set tech(9T,lib,ss_0p80v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p80v_m40c.lib_ccs_tn.gz"]
set tech(9T,lib,ss_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ss_nominal_max_0p90v_125c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ss_nominal_max_0p90v_125c.lib"]
set tech(9T,lib,ss_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_ss_nominal_max_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_ss_nominal_max_0p90v_m40c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_ss_nominal_max_0p90v_m40c.lib"]
set tech(9T,lib,tt_0p90v_125c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_125c.lib_ccs_tn.gz"]
set tech(9T,lib,tt_0p90v_25c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/Front_End/timing/memory/sram28slpe_tt_nominal_typ_0p90v_25c.lib" "/tmp/test_libs/gf_28nm/Front_End/timing/io/io28slpe_tt_nominal_typ_0p90v_25c.lib"]
set tech(9T,lib,tt_0p90v_m40c,timing) [list "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz" "/tmp/test_libs/gf_28nm/lib-ccs-tn/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_m40c.lib_ccs_tn.gz"]

