#!/usr/bin/env tclsh
# =============================================================================
# AUTO-GENERATED by: cbflow flow library-manager generate
# Tech: gf_28nm | Generated: 2026-06-04 20:07
# Source: /tmp/test_libs/gf_28nm
# Tracks: 7T 9T | VTs: rvt lvt ulvt hvt
# Corners: 0
# DO NOT EDIT — regenerate with: cbflow flow library-manager generate
# =============================================================================

# ── NDM per track per VT ──
set tech(7T,rvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_rvt_c30.ndm"]
set tech(7T,lvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_lvt_c30.ndm"]
set tech(7T,ulvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_ulvt_c30.ndm"]
set tech(7T,hvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_hvt_c30.ndm"]
set tech(9T,rvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_rvt_c30.ndm"]
set tech(9T,lvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_lvt_c30.ndm"]
set tech(9T,ulvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_ulvt_c30.ndm"]
set tech(9T,hvt,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_hvt_c30.ndm"]

# ── NDM shared ──
set tech(ndm,memory) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sram28slpe_memory.ndm"]
set tech(ndm,io) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/io28slpe_io.ndm"]
set tech(ndm,analog) [list]

# ── NDM combined per track ──
set tech(7T,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_rvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_lvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_ulvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc7mcz_28slpe_base_hvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sram28slpe_memory.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/io28slpe_io.ndm"]
set tech(9T,ndm) [list "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_rvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_lvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_ulvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sc9mcz_28slpe_base_hvt_c30.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/sram28slpe_memory.ndm" "/tmp/test_libs/gf_28nm/Back_End/ndm/io28slpe_io.ndm"]

# ── DB per track per VT ──
set tech(7T,rvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(7T,lvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(7T,ulvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(7T,hvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,rvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,lvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,ulvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,hvt,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]

# ── DB shared ──
set tech(db,memory) [list ]
set tech(db,io) [list ]

# ── DB combined per track ──
set tech(7T,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc7mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]
set tech(9T,db) [list "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_rvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_lvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_ulvt_c30_tt_nominal_typ_0p90v_25c.db" "/tmp/test_libs/gf_28nm/Front_End/timing/stdcell/sc9mcz_28slpe_base_hvt_c30_tt_nominal_typ_0p90v_25c.db"]

# ── lib_nom per track per VT ──

# ── lib_nom shared ──
set tech(lib_nom,memory) [list ]
set tech(lib_nom,io) [list ]

# ── lib_nom combined per track (from TT nominal: none) ──
set tech(7T,lib_nom) [list ]
set tech(9T,lib_nom) [list ]

# ── LEF per track per VT ──
set tech(7T,rvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_rvt_c30.lef"]
set tech(7T,lvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_lvt_c30.lef"]
set tech(7T,ulvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_ulvt_c30.lef"]
set tech(7T,hvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_hvt_c30.lef"]
set tech(9T,rvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_rvt_c30.lef"]
set tech(9T,lvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_lvt_c30.lef"]
set tech(9T,ulvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_ulvt_c30.lef"]
set tech(9T,hvt,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_hvt_c30.lef"]

# ── LEF shared ──
set tech(lef,memory) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sram28slpe_memory.lef"]
set tech(lef,io) [list "/tmp/test_libs/gf_28nm/Back_End/lef/io28slpe_io.lef"]

# ── LEF combined per track ──
set tech(7T,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_rvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_lvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_ulvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc7mcz_28slpe_base_hvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sram28slpe_memory.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/io28slpe_io.lef"]
set tech(9T,lef) [list "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_rvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_lvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_ulvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sc9mcz_28slpe_base_hvt_c30.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/sram28slpe_memory.lef" "/tmp/test_libs/gf_28nm/Back_End/lef/io28slpe_io.lef"]

# ── Corners discovered ──
set tech(corners) {}

# ── Timing libs per track per VT per corner ──

# ── Timing libs shared per corner (memory + IO) ──

# ── Timing combined per track per corner ──

