#!/usr/bin/env tclsh
# CBFlow SCAN_INSERT release_data — dft_compiler

set run_dir $::env(CBFLOW_RUN_DIR)
source "$run_dir/.run.cbflow.tcl"
source "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/utils.tcl"

set FLOW_TYPE "SCAN_INSERT"
set STAGE_NAME "release_data"
set NODE_NAME "${STAGE_NAME}1"

source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/config.tcl"
source "$run_dir/work/$FLOW_TYPE/$NODE_NAME/run/setup.tcl"
setup_dirs $run_dir $FLOW_TYPE $NODE_NAME

set _rel "$::env(FLOW_DIR)/utils/utilities/$::env(UTILITIES_VERSION)/release_utils.tcl"
if {[file exists $_rel]} { source $_rel }

flow_proc release_data_run {
    handle_info "SCAN_INSERT release_data (dft_compiler) running..."
    # test_mode dummy outputs are auto-generated by handler_run/launch_utils.tcl.
    # Real-tool integration goes here.
    if {[info commands ::CBFlow::Release::stage_release_data] ne ""} {
        ::CBFlow::Release::stage_release_data SCAN_INSERT $run_dir
    }
    handle_info "SCAN_INSERT release_data completed"
}
flow_proc release_data_flow { flow_exec release_data_run }
if {[info exists argv0] && $argv0 eq [info script]} { flow_exec release_data_flow } else { puts " SCAN_INSERT release_data procedures loaded" }
exit
