#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# CBflow STA — extraction Subnode Handler (Cadence Tempus / Quantus)
# Dynamic subnodes: setup, rc_max, rc_min, rc_typ, ..., validate, finish
# Each rc_* subnode generates a per-corner command file in corner/run/
# ═══════════════════════════════════════════════════════════════════════════════

source "$::env(SCRIPTS_ROOT)/utilities/$::env(UTILITIES_VERSION)/handler_common.tcl"
source "$::env(SCRIPTS_ROOT)/utilities/$::env(UTILITIES_VERSION)/launch_utils.tcl"

lassign [handler_parse_args $argv $argc] subnode_name run_dir node_name
handler_load_configs $run_dir "STA"

set ::flow_type "STA"
set stage_name "extraction"
if {$node_name eq ""} { set node_name "${stage_name}1" }

set test_mode [handler_is_test_mode]

switch $subnode_name {
    "setup" {
        puts "INFO: $stage_name setup..."
        handler_setup $run_dir $::flow_type $node_name
        puts "INFO: $stage_name setup completed"
    }
    "validate" {
        puts "INFO: $stage_name validate..."
        handler_validate $run_dir $::flow_type $node_name $stage_name $test_mode
        puts "INFO: $stage_name validate completed"
    }
    "finish" {
        puts "INFO: $stage_name finish..."
        handler_finish $run_dir $::flow_type $node_name $stage_name
        puts "INFO: $stage_name finish completed"
    }
    default {
        # Dynamic RC corner subnode (e.g., rc_max, rc_typ, rc_min, rc_max_cworst)
        if {![string match "rc_*" $subnode_name]} {
            puts "ERROR: Unknown subnode: $subnode_name (expected rc_* corner)"
            exit 1
        }

        set rc_corner $subnode_name
        puts "INFO: extraction corner: $rc_corner"

        # Corner directory structure
        set _corner_dir "$run_dir/work/$::flow_type/$node_name/$rc_corner"
        set _run_dir "$_corner_dir/run"
        set _reports_dir "$_corner_dir/reports"
        set _outputs_dir "$_corner_dir/outputs"
        file mkdir $_run_dir
        file mkdir $_reports_dir
        file mkdir $_outputs_dir

        # Resolve RC tech file: priority qrc > nxtgrd > tluplus
        set _rc_file ""
        set _rc_file_type ""
        foreach _fmt {qrc nxtgrd tluplus} {
            if {$_rc_file eq "" && [info exists ::tech(rcx,${rc_corner},${_fmt})] && $::tech(rcx,${rc_corner},${_fmt}) ne ""} {
                set _rc_file $::tech(rcx,${rc_corner},${_fmt})
                set _rc_file_type $_fmt
            }
        }

        # SPEF output path
        set _spef_file "$_outputs_dir/$::flow(design_name).${rc_corner}.spef"

        # Resolve inputs for QRC command file
        set _lef_file ""
        if {[info exists ::tech(lef_tech)]} { set _lef_file $::tech(lef_tech) }

        # Cell LEFs — track resolved at runtime via config.tcl
        set _cell_lefs [list]
        if {[info exists ::project(track_variant)]} {
            set _trk $::project(track_variant)
            if {[info exists ::tech(${_trk},lef)]} {
                foreach _l $::tech(${_trk},lef) {
                    if {$_l ne ""} { lappend _cell_lefs $_l }
                }
            }
        }

        set _def_file ""
        if {[info exists ::sta(input,def_file)]} { set _def_file $::sta(input,def_file) }

        set _netlist ""
        if {[info exists ::sta(input,netlist)]} { set _netlist $::sta(input,netlist) }

        # ── Generate QRC/Quantus command file ──
        set _cmd_file "$_run_dir/${rc_corner}.quantus.cmd"
        set _fh [open $_cmd_file "w"]

        puts $_fh "// ================================================================"
        puts $_fh "// QRC/Quantus Extraction — RC Corner: $rc_corner"
        puts $_fh "// Generated by CBflow extraction subnode handler"
        puts $_fh "// Launch: quantus -cmd $rc_corner.cmd"
        puts $_fh "// ================================================================"
        puts $_fh ""

        # QRC tech file
        if {$_rc_file ne ""} {
            puts $_fh "extract_typ_file $_rc_file"
        }
        puts $_fh ""

        # LEF files
        if {$_lef_file ne ""} {
            puts $_fh "lef_file $_lef_file"
        }
        foreach _cl $_cell_lefs {
            puts $_fh "lef_file $_cl"
        }
        puts $_fh ""

        # Design inputs
        if {$_def_file ne ""} {
            puts $_fh "def_file $_def_file"
        }
        if {$_netlist ne ""} {
            puts $_fh "spice_netlist $_netlist"
        }
        puts $_fh ""

        # Output
        puts $_fh "output_name $_spef_file"
        puts $_fh "output_format SPEF"
        puts $_fh ""

        # Extraction settings
        puts $_fh "coupled_extraction YES"
        if {[info exists ::sta(extraction,effort)] && $::sta(extraction,effort) ne ""} {
            puts $_fh "extraction_effort_level $::sta(extraction,effort)"
        }
        if {[info exists ::sta(extraction,coupling_cap_threshold)]} {
            puts $_fh "coupling_c_threshold $::sta(extraction,coupling_cap_threshold)"
        }
        puts $_fh ""

        # Multi-CPU
        if {[info exists ::sta(common,cpu_count)] && $::sta(common,cpu_count) ne ""} {
            puts $_fh "num_cores $::sta(common,cpu_count)"
        }
        puts $_fh ""

        # Log
        puts $_fh "log_file $_run_dir/${rc_corner}.log"
        puts $_fh ""

        close $_fh
        puts "INFO: Generated QRC command file: $_cmd_file"

        # ── Execute or stub ──
        if {$test_mode} {
            puts "INFO: \[TEST MODE\] Extraction corner: $rc_corner"
            puts "INFO:   RC file:   $_rc_file ($_rc_file_type)"
            puts "INFO:   QRC cmd:   $_cmd_file"
            # Create mock SPEF
            set fh [open $_spef_file "w"]
            puts $fh "// SPEF for $rc_corner extraction"
            puts $fh "// Corner: $rc_corner  Design: $::flow(design_name)"
            puts $fh "// RC file: $_rc_file ($_rc_file_type)"
            puts $fh "// Generated: [clock format [clock seconds]]"
            close $fh
            puts "INFO: Mock SPEF: $_spef_file"
        } else {
            # Launch Quantus with the generated QRC command file
            set _quantus_bin "quantus"
            if {[info exists ::sta(extraction,quantus_binary)]} {
                set _quantus_bin $::sta(extraction,quantus_binary)
            }
            set _log "$_run_dir/${rc_corner}.log"
            puts "INFO: Launching: $_quantus_bin -cmd $_cmd_file"
            if {[catch {exec $_quantus_bin -cmd $_cmd_file >& $_log} result]} {
                puts "ERROR: QRC extraction $rc_corner failed: $result"
                puts "ERROR: Log: $_log"
                exit 1
            }
        }
        puts "INFO: extraction $rc_corner done"
    }
}
