set project(name)        "ravendrive"
set project(phase)       "P0"
set flow(type)           "LEC"
set flow(design_name)    "cpu_core"
set flow(run_name)       "lec_test"
set flow(test_mode)      "true"

set lec(input,netlist_golden)  "/Users/vmerugu/projects/CBflow_clone/netlist_golden.v"
set lec(input,netlist_revised) "/Users/vmerugu/projects/CBflow_clone/netlist_revised.v"
set lec(input,sdc_file)        "/Users/vmerugu/projects/CBflow_clone/func.sdc"
