#!/usr/bin/env tclsh
# ═══════════════════════════════════════════════════════════════════════════════
# CBflow Technology Configuration — TSMC N5 (5nm FinFET)
# ALL track heights (5T, 6T, 7T) in ONE file — flow picks via tech(track)
# Library sets auto-generated in lib_config.tcl by library-manager
# ═══════════════════════════════════════════════════════════════════════════════

set _tech_dir [file dirname [file normalize [info script]]]

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1: TECHNOLOGY IDENTITY
# ═══════════════════════════════════════════════════════════════════════════════

set tech(node)        "5nm"
set tech(process)     "TSMC N5"
set tech(foundry)     "TSMC"
set tech(tracks_available) "5T 6T 7T"

# ── VT Variant Patterns (for dont_use selection + lib filtering) ───────
set tech(vt_variants_available) {svt lvt ulvt hvt}
set tech(vt_pattern,svt)  "*svt*"
set tech(vt_pattern,lvt)  "*lvt*"
set tech(vt_pattern,ulvt) "*ulvt*"
set tech(vt_pattern,hvt)  "*hvt*"




# ── Library root ───────────────────────────────────────────────────────
set tech(lib_root) "/tmp/test_libs/tsmc_5nm"
set _R "$tech(lib_root)"

# Additional lib paths (multiple roots — auto-read by library-manager generate)
set tech(lib_paths,stdcell) [list]
set tech(lib_paths,memory) [list]
set tech(lib_paths,io) [list]

# ── Load per-metal-stack configuration ────────────────────────────────
set _ms_file "$_tech_dir/metal_stack/$project(metal_stack).tcl"
if {![file exists $_ms_file]} {
    puts "ERROR: Metal stack config not found: $_ms_file"
    puts "       Create: config/tech/tsmc_5nm/v1.0.0/metal_stack/$project(metal_stack).tcl"
    exit 1
}
source $_ms_file

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2: ACTIVE TRACK + VT FLAVORS
# ═══════════════════════════════════════════════════════════════════════════════

if {![info exists project(track_variant)] || $project(track_variant) eq ""} {
    puts "ERROR: project(track_variant) not set. Define it in your project_config.tcl"
    puts "       Technology: $tech(process) | Available tracks: $tech(tracks_available)"
    exit 1
}
if {[lsearch -exact $tech(tracks_available) $project(track_variant)] == -1} {
    puts "ERROR: Invalid track '$project(track_variant)' for $tech(process)"
    puts "       Available tracks: $tech(tracks_available)"
    exit 1
}
set tech(track) $project(track_variant)

if {![info exists project(vt_flavors)] || $project(vt_flavors) eq ""} {
    puts "ERROR: project(vt_flavors) not set. Define it in project_config.tcl"
    puts "       Available: $tech(vt_variants_available)"
    exit 1
}
set _vt_load $project(vt_flavors)
set tech(vt_flavors_loaded) $_vt_load

puts "INFO: $tech(process) active track: $tech(track), VT flavors: $_vt_load"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3: LIBRARY SETS (sourced from generated lib_config.tcl)
# Generated by: cbflow flow library-manager generate --lib-root <path> --tech tsmc_5nm
# Contains: NDM, DB, LEF, lib_nom, per-corner timing — fully resolved paths
# ═══════════════════════════════════════════════════════════════════════════════

set tech(lef_tech) "$_R/Back_End/lef/tsmc5nm_tech.lef"

if {[info exists project(lib_config_version)] && $project(lib_config_version) ne ""} {
    set _lib_config "$_tech_dir/lib_config_$project(lib_config_version).tcl"
} else {
    set _lib_config "$_tech_dir/lib_config.tcl"
}
if {![file exists $_lib_config]} {
    puts "ERROR: lib_config not found: $_lib_config"
    puts "       Run: cbflow flow library-manager generate --tech tsmc_5nm"
    exit 1
}
source $_lib_config

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4: PARASITIC EXTRACTION (shared — same for all tracks)
# ═══════════════════════════════════════════════════════════════════════════════

set tech(tluplus_map) "$_R/Back_End/rcx/tsmc5nm_tf_itf_tluplus.map"

set tech(rcx,rc_max,tluplus)   "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmax.tluplus"
set tech(rcx,rc_max,nxtgrd)    "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmax.nxtgrd"
set tech(rcx,rc_max,qrc)       "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmax.qrcTechFile"

set tech(rcx,rc_typ,tluplus)   "$_R/Back_End/rcx/tsmc5nm_1p13m_Ctyp.tluplus"
set tech(rcx,rc_typ,nxtgrd)    "$_R/Back_End/rcx/tsmc5nm_1p13m_Ctyp.nxtgrd"
set tech(rcx,rc_typ,qrc)       "$_R/Back_End/rcx/tsmc5nm_1p13m_Ctyp.qrcTechFile"

set tech(rcx,rc_min,tluplus)   "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmin.tluplus"
set tech(rcx,rc_min,nxtgrd)    "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmin.nxtgrd"
set tech(rcx,rc_min,qrc)       "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmin.qrcTechFile"

set tech(rcx,rc_max_cworst,tluplus) "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmax.tluplus"
set tech(rcx,rc_max_cworst,nxtgrd)  "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmax.nxtgrd"
set tech(rcx,rc_max_cworst,qrc)     "$_R/Back_End/rcx/tsmc5nm_1p13m_Cmax.qrcTechFile"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 5: PHYSICAL CELLS (per track — site, fillers, CTS, tap, endcap)
# ═══════════════════════════════════════════════════════════════════════════════

# ── 5T Physical ──
set tech(5T,site)           "TSMC_N5_SC5T"
set tech(5T,cell_height)    "0.216"
set tech(5T,site_width)     "0.051"
set tech(5T,fillers)        "TSMC_N5_SC5T_FILL1 TSMC_N5_SC5T_FILL2 TSMC_N5_SC5T_FILL4 TSMC_N5_SC5T_FILL8"
set tech(5T,well_tap)       "TSMC_N5_SC5T_FILLTIE1"
set tech(5T,endcap)         "TSMC_N5_SC5T_ENDCAP1"
set tech(5T,decap)          "TSMC_N5_SC5T_DCAP4 TSMC_N5_SC5T_DCAP8"
set tech(5T,clock_buffers)  "tcbn05bwp5tsvt_CKBUF4 tcbn05bwp5tsvt_CKBUF8"
set tech(5T,clock_inverters) "tcbn05bwp5tsvt_CKINV4 tcbn05bwp5tsvt_CKINV8"
set tech(5T,hold_buffers)   "tcbn05bwp5tsvt_BUFFD1 tcbn05bwp5tsvt_BUFFD2 tcbn05bwp5tsvt_BUFFD4"
set tech(5T,delay_cells)    "tcbn05bwp5tsvt_DEL1 tcbn05bwp5tsvt_DEL2 tcbn05bwp5tsvt_DEL4"
set tech(5T,icg_cells)      "tcbn05bwp5tsvt_CKLNQD1 tcbn05bwp5tsvt_CKLNQD2 tcbn05bwp5tsvt_CKLNQD4"
set tech(5T,power_switch)   "tcbn05bwp5tsvt_HDRDWN1 tcbn05bwp5tsvt_HDRDWN2 tcbn05bwp5tsvt_HDRDWN4"
set tech(5T,isolation)      "tcbn05bwp5tsvt_ISOLAND1 tcbn05bwp5tsvt_ISOLOR1 tcbn05bwp5tsvt_ISOLAND2 tcbn05bwp5tsvt_ISOLOR2"
set tech(5T,level_shifter)  "tcbn05bwp5tsvt_LSDOWN1 tcbn05bwp5tsvt_LSUP1 tcbn05bwp5tsvt_LSDOWN2 tcbn05bwp5tsvt_LSUP2"
set tech(5T,tie_cells)      "tcbn05bwp5tsvt_TIEHI tcbn05bwp5tsvt_TIELO"
set tech(5T,dont_use)       "*D0BWP5T* *OPTHOLD* *DEL*"

# ── 6T Physical ──
set tech(6T,site)           "TSMC_N5_SC6T"
set tech(6T,cell_height)    "0.270"
set tech(6T,site_width)     "0.051"
set tech(6T,fillers)        "TSMC_N5_SC6T_FILL1 TSMC_N5_SC6T_FILL2 TSMC_N5_SC6T_FILL4 TSMC_N5_SC6T_FILL8"
set tech(6T,well_tap)       "TSMC_N5_SC6T_FILLTIE1"
set tech(6T,endcap)         "TSMC_N5_SC6T_ENDCAP1"
set tech(6T,decap)          "TSMC_N5_SC6T_DCAP4 TSMC_N5_SC6T_DCAP8"
set tech(6T,clock_buffers)  "tcbn05bwp6tsvt_CKBUF4 tcbn05bwp6tsvt_CKBUF8"
set tech(6T,clock_inverters) "tcbn05bwp6tsvt_CKINV4 tcbn05bwp6tsvt_CKINV8"
set tech(6T,hold_buffers)   "tcbn05bwp6tsvt_BUFFD1 tcbn05bwp6tsvt_BUFFD2 tcbn05bwp6tsvt_BUFFD4"
set tech(6T,delay_cells)    "tcbn05bwp6tsvt_DEL1 tcbn05bwp6tsvt_DEL2 tcbn05bwp6tsvt_DEL4"
set tech(6T,icg_cells)      "tcbn05bwp6tsvt_CKLNQD1 tcbn05bwp6tsvt_CKLNQD2 tcbn05bwp6tsvt_CKLNQD4"
set tech(6T,power_switch)   "tcbn05bwp6tsvt_HDRDWN1 tcbn05bwp6tsvt_HDRDWN2 tcbn05bwp6tsvt_HDRDWN4"
set tech(6T,isolation)      "tcbn05bwp6tsvt_ISOLAND1 tcbn05bwp6tsvt_ISOLOR1 tcbn05bwp6tsvt_ISOLAND2 tcbn05bwp6tsvt_ISOLOR2"
set tech(6T,level_shifter)  "tcbn05bwp6tsvt_LSDOWN1 tcbn05bwp6tsvt_LSUP1 tcbn05bwp6tsvt_LSDOWN2 tcbn05bwp6tsvt_LSUP2"
set tech(6T,tie_cells)      "tcbn05bwp6tsvt_TIEHI tcbn05bwp6tsvt_TIELO"
set tech(6T,dont_use)       "*D0BWP6T* *OPTHOLD* *DEL*"

# ── 7T Physical ──
set tech(7T,site)           "TSMC_N5_SC7T"
set tech(7T,cell_height)    "0.324"
set tech(7T,site_width)     "0.051"
set tech(7T,fillers)        "TSMC_N5_SC7T_FILL1 TSMC_N5_SC7T_FILL2 TSMC_N5_SC7T_FILL4 TSMC_N5_SC7T_FILL8"
set tech(7T,well_tap)       "TSMC_N5_SC7T_FILLTIE1"
set tech(7T,endcap)         "TSMC_N5_SC7T_ENDCAP1"
set tech(7T,decap)          "TSMC_N5_SC7T_DCAP4 TSMC_N5_SC7T_DCAP8"
set tech(7T,clock_buffers)  "tcbn05bwp7tsvt_CKBUF4 tcbn05bwp7tsvt_CKBUF8"
set tech(7T,clock_inverters) "tcbn05bwp7tsvt_CKINV4 tcbn05bwp7tsvt_CKINV8"
set tech(7T,hold_buffers)   "tcbn05bwp7tsvt_BUFFD1 tcbn05bwp7tsvt_BUFFD2 tcbn05bwp7tsvt_BUFFD4"
set tech(7T,delay_cells)    "tcbn05bwp7tsvt_DEL1 tcbn05bwp7tsvt_DEL2 tcbn05bwp7tsvt_DEL4"
set tech(7T,icg_cells)      "tcbn05bwp7tsvt_CKLNQD1 tcbn05bwp7tsvt_CKLNQD2 tcbn05bwp7tsvt_CKLNQD4"
set tech(7T,power_switch)   "tcbn05bwp7tsvt_HDRDWN1 tcbn05bwp7tsvt_HDRDWN2 tcbn05bwp7tsvt_HDRDWN4"
set tech(7T,isolation)      "tcbn05bwp7tsvt_ISOLAND1 tcbn05bwp7tsvt_ISOLOR1 tcbn05bwp7tsvt_ISOLAND2 tcbn05bwp7tsvt_ISOLOR2"
set tech(7T,level_shifter)  "tcbn05bwp7tsvt_LSDOWN1 tcbn05bwp7tsvt_LSUP1 tcbn05bwp7tsvt_LSDOWN2 tcbn05bwp7tsvt_LSUP2"
set tech(7T,tie_cells)      "tcbn05bwp7tsvt_TIEHI tcbn05bwp7tsvt_TIELO"
set tech(7T,dont_use)       "*D0BWP7T* *OPTHOLD* *DEL*"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 6: DESIGN RULES & ROUTING
# ═══════════════════════════════════════════════════════════════════════════════

set tech(min_routing_layer) "M1"
set tech(max_routing_layer) "M12"
set tech(clock_routing_layer_min) "M4"
set tech(clock_routing_layer_max) "M10"

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 7: SIGNOFF, DRC & GDS
# ═══════════════════════════════════════════════════════════════════════════════

set tech(gds_layer_map_file)        "$_R/Back_End/layermap/tsmc5nm_layermap.map"
set tech(antenna_rule_file)         "$_R/Back_End/antenna/tsmc5nm_antenna.rules"
set tech(lib_cell_purpose_file)     ""
set tech(filler_sidefile)           ""
set tech(signal_em_constraint_file) ""
set tech(signal_em_constraint_format) "sigem"
set tech(stream_files_for_merge)    ""

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 8: BACKWARD COMPATIBILITY — old variable names -> new
# ═══════════════════════════════════════════════════════════════════════════════

set _trk $tech(track)
if {[info exists tech(${_trk},ndm)] && [llength $tech(${_trk},ndm)] > 0} {
    set tech(ndm,standard_cells) [lindex $tech(${_trk},ndm) 0]
}
if {[info exists tech(${_trk},lef)] && [llength $tech(${_trk},lef)] > 0} {
    set tech(lef,standard_cells) [lindex $tech(${_trk},lef) 0]
}
set tech(library,root_path)    $tech(lib_root)
set tech(library,stdcell_path) "$tech(lib_root)/Front_End/timing/stdcell"
set tech(library,memory_path)  "$tech(lib_root)/Front_End/timing/memory"
set tech(library,io_path)      "$tech(lib_root)/Front_End/timing/io"

set tech(lef,technology) $tech(lef_tech)

if {[info exists tech(${_trk},lib_nom)]} {
    set tech(lib,timing) $tech(${_trk},lib_nom)
}

if {[info exists tech(${_trk},decap)]} {
    set tech(decap_cells) $tech(${_trk},decap)
}

puts "INFO: $tech(process) tech config loaded — track=$tech(track), VT=$tech(vt_flavors_loaded), metal=$project(metal_stack), libs=[expr {[info exists tech(${_trk},ndm)] ? [llength $tech(${_trk},ndm)] : 0}] NDMs"
